import type { DataExportArchiveRows } from './data-export-archive-mappers';

type NullableDate = Date | null;

export function mapDataExportArchive(
  rows: DataExportArchiveRows,
): Readonly<Record<string, unknown>> {
  return {
    schemaVersion: 1,
    exportId: rows.exportId,
    generatedAt: rows.generatedAt,
    workspace: mapWorkspace(rows.workspace),
    memberships: rows.memberships.map((row) => ({
      id: row.id,
      userId: row.userId,
      email: row.user.email,
      displayName: row.user.displayName,
      role: row.role,
      state: row.state,
      brandScope: row.brandScope,
      invitedAt: iso(row.invitedAt),
      acceptedAt: iso(row.acceptedAt),
      removedAt: iso(row.removedAt),
      createdAt: row.createdAt.toISOString(),
      updatedAt: row.updatedAt.toISOString(),
    })),
    brands: rows.brands.map((row) => ({
      id: row.id,
      name: row.name,
      slug: row.slug,
      voice: row.voice,
      audience: row.audience,
      approvedClaims: row.approvedClaims,
      blockedTerms: row.blockedTerms,
      domains: row.domains,
      defaultTimeZone: row.defaultTimeZone,
      archivedAt: iso(row.archivedAt),
      createdAt: row.createdAt.toISOString(),
      updatedAt: row.updatedAt.toISOString(),
    })),
    campaigns: rows.campaigns.map((row) => ({
      id: row.id,
      brandId: row.brandId,
      name: row.name,
      objective: row.objective,
      tags: row.tags,
      startsAt: iso(row.startsAt),
      endsAt: iso(row.endsAt),
      archivedAt: iso(row.archivedAt),
      createdAt: row.createdAt.toISOString(),
      updatedAt: row.updatedAt.toISOString(),
    })),
    contentItems: rows.contentItems.map((row) => ({
      id: row.id,
      brandId: row.brandId,
      campaignId: row.campaignId,
      title: row.title,
      brief: row.brief,
      state: row.state,
      approvalPolicy: row.approvalPolicy,
      currentVersionId: row.currentVersionId,
      approvedVersionId: row.approvedVersionId,
      scheduledAt: iso(row.scheduledAt),
      scheduledTimeZone: row.scheduledTimeZone,
      approvedAt: iso(row.approvedAt),
      publishedAt: iso(row.publishedAt),
      canceledAt: iso(row.canceledAt),
      repeatEveryDays: row.repeatEveryDays,
      repeatUntil: iso(row.repeatUntil),
      repeatCount: row.repeatCount,
      repeatOfItemId: row.repeatOfItemId,
      surface: row.surface,
      creationMethod: row.creationMethod,
      createdByUserId: row.createdByUserId,
      createdAt: row.createdAt.toISOString(),
      updatedAt: row.updatedAt.toISOString(),
    })),
    contentVersions: rows.versions.map((row) => ({
      id: row.id,
      contentItemId: row.contentItemId,
      version: row.version,
      body: row.body,
      contentHash: row.contentHash,
      locale: row.locale,
      creationMethod: row.creationMethod,
      sourceIds: row.sourceIds,
      createdByUserId: row.createdByUserId,
      createdAt: row.createdAt.toISOString(),
    })),
    postVariants: rows.variants.map((row) => ({
      id: row.id,
      contentItemId: row.contentItemId,
      contentVersionId: row.contentVersionId,
      connectionId: row.connectionId,
      destinationId: row.destinationId,
      provider: row.provider,
      locale: row.locale,
      body: row.body,
      mediaAssetIds: row.mediaAssetIds,
      signatureId: row.signatureId,
      inheritedFields: row.inheritedFields,
      overriddenFields: row.overriddenFields,
      state: row.state,
      capabilitySnapshotVersion: row.capabilitySnapshotVersion,
      createdAt: row.createdAt.toISOString(),
      updatedAt: row.updatedAt.toISOString(),
    })),
    connections: rows.connections.map((row) => ({
      id: row.id,
      brandId: row.brandId,
      provider: row.provider,
      accountType: row.accountType,
      displayName: row.displayName,
      handle: row.handle,
      avatarUrl: row.avatarUrl,
      profileUrl: row.profileUrl,
      status: row.status,
      statusReason: row.statusReason,
      grantedScopes: row.grantedScopes,
      capabilityVersion: row.capabilityVersion,
      capabilitiesRefreshedAt: iso(row.capabilitiesRefreshedAt),
      connectedAt: row.connectedAt.toISOString(),
      disconnectedAt: iso(row.disconnectedAt),
      createdAt: row.createdAt.toISOString(),
      updatedAt: row.updatedAt.toISOString(),
    })),
    media: rows.media.map((row) => ({
      id: row.id,
      brandId: row.brandId,
      kind: row.kind,
      mimeType: row.mimeType,
      byteSize: row.byteSize.toString(),
      checksumSha256: row.checksumSha256,
      width: row.width,
      height: row.height,
      durationMs: row.durationMs,
      altText: row.altText,
      rights: row.rights,
      originKind: row.originKind,
      originUrl: row.originUrl,
      scanState: row.scanState,
      retentionExpiresAt: row.retentionExpiresAt.toISOString(),
      storageDeletedAt: iso(row.storageDeletedAt),
      deletedAt: iso(row.deletedAt),
      createdAt: row.createdAt.toISOString(),
      updatedAt: row.updatedAt.toISOString(),
    })),
    publishJobs: rows.jobs.map((row) => ({
      id: row.id,
      contentItemId: row.contentItemId,
      contentVersionId: row.contentVersionId,
      postVariantId: row.postVariantId,
      connectionId: row.connectionId,
      approvalRequestId: row.approvalRequestId,
      approvalPolicy: row.approvalPolicy,
      scheduledFor: row.scheduledFor.toISOString(),
      scheduledTimeZone: row.scheduledTimeZone,
      state: row.state,
      attemptCount: row.attemptCount,
      lastErrorClass: row.lastErrorClass,
      lastErrorCode: row.lastErrorCode,
      surface: row.surface,
      dispatchedAt: iso(row.dispatchedAt),
      completedAt: iso(row.completedAt),
      canceledAt: iso(row.canceledAt),
      createdAt: row.createdAt.toISOString(),
      updatedAt: row.updatedAt.toISOString(),
    })),
    publicationReceipts: rows.receipts.map((row) => ({
      id: row.id,
      publishJobId: row.publishJobId,
      contentVersionId: row.contentVersionId,
      connectionId: row.connectionId,
      provider: row.provider,
      externalPostId: row.externalPostId,
      permalink: row.permalink,
      contentHash: row.contentHash,
      mediaChecksums: row.mediaChecksums,
      publishedShortLinks: row.publishedShortLinks,
      publishedAt: row.publishedAt.toISOString(),
      dispatchedAt: iso(row.dispatchedAt),
      scheduledFor: iso(row.scheduledFor),
      scheduledTimeZone: row.scheduledTimeZone,
      surface: row.surface,
      approvedByUserId: row.approvedByUserId,
      approvalPolicy: row.approvalPolicy,
      costActualMinor: row.costActualMinor,
      costCurrency: row.costCurrency,
      deletedExternallyAt: iso(row.deletedExternallyAt),
      lastAnalyticsSyncAt: iso(row.lastAnalyticsSyncAt),
      createdAt: row.createdAt.toISOString(),
    })),
    auditReferences: rows.audits.map((row) => ({
      id: row.id,
      actorType: row.actorType,
      actorId: row.actorId,
      surface: row.surface,
      action: row.action,
      targetType: row.targetType,
      targetId: row.targetId,
      beforeHash: row.beforeHash,
      afterHash: row.afterHash,
      correlationId: row.correlationId,
      createdAt: row.createdAt.toISOString(),
    })),
  };
}

function iso(value: NullableDate): string | null {
  return value?.toISOString() ?? null;
}

function mapWorkspace(row: DataExportArchiveRows['workspace']): Readonly<Record<string, unknown>> {
  return {
    id: row.id,
    name: row.name,
    slug: row.slug,
    ownerUserId: row.ownerUserId,
    status: row.status,
    defaultLocale: row.defaultLocale,
    defaultTimeZone: row.defaultTimeZone,
    contentLocales: row.contentLocales,
    markets: row.markets,
    weekStart: row.weekStart,
    hourCycle: row.hourCycle,
    createdAt: row.createdAt.toISOString(),
    updatedAt: row.updatedAt.toISOString(),
  };
}
