import type { Db } from '../internal/runtime';
import { notFound } from '../internal/errors';
import { mapDataExportArchive } from './data-export-archive-format';

const workspaceSelect = {
  id: true,
  name: true,
  slug: true,
  ownerUserId: true,
  status: true,
  defaultLocale: true,
  defaultTimeZone: true,
  contentLocales: true,
  markets: true,
  weekStart: true,
  hourCycle: true,
  createdAt: true,
  updatedAt: true,
} as const;

export async function readDataExportArchive(
  db: Db,
  input: { readonly workspaceId: string; readonly exportId: string; readonly generatedAt: string },
): Promise<Readonly<Record<string, unknown>>> {
  const workspace = await db.workspace.findFirst({
    where: { id: input.workspaceId },
    select: workspaceSelect,
  });
  if (workspace === null) {
    throw notFound('workspace', input.workspaceId);
  }

  const [
    memberships,
    brands,
    campaigns,
    contentItems,
    versions,
    variants,
    connections,
    media,
    jobs,
    receipts,
    audits,
  ] = await Promise.all([
    db.membership.findMany({
      where: { workspaceId: input.workspaceId },
      orderBy: { id: 'asc' },
      select: {
        id: true,
        userId: true,
        role: true,
        state: true,
        brandScope: true,
        invitedAt: true,
        acceptedAt: true,
        removedAt: true,
        createdAt: true,
        updatedAt: true,
        user: { select: { id: true, email: true, displayName: true } },
      },
    }),
    db.brand.findMany({
      where: { workspaceId: input.workspaceId },
      orderBy: { id: 'asc' },
      select: {
        id: true,
        name: true,
        slug: true,
        voice: true,
        audience: true,
        approvedClaims: true,
        blockedTerms: true,
        domains: true,
        defaultTimeZone: true,
        archivedAt: true,
        createdAt: true,
        updatedAt: true,
      },
    }),
    db.campaign.findMany({
      where: { workspaceId: input.workspaceId },
      orderBy: { id: 'asc' },
      select: {
        id: true,
        brandId: true,
        name: true,
        objective: true,
        tags: true,
        startsAt: true,
        endsAt: true,
        archivedAt: true,
        createdAt: true,
        updatedAt: true,
      },
    }),
    db.contentItem.findMany({
      where: { workspaceId: input.workspaceId },
      orderBy: { id: 'asc' },
      select: {
        id: true,
        brandId: true,
        campaignId: true,
        title: true,
        brief: true,
        state: true,
        approvalPolicy: true,
        currentVersionId: true,
        approvedVersionId: true,
        scheduledAt: true,
        scheduledTimeZone: true,
        approvedAt: true,
        publishedAt: true,
        canceledAt: true,
        repeatEveryDays: true,
        repeatUntil: true,
        repeatCount: true,
        repeatOfItemId: true,
        surface: true,
        creationMethod: true,
        createdByUserId: true,
        createdAt: true,
        updatedAt: true,
      },
    }),
    db.contentVersion.findMany({
      where: { workspaceId: input.workspaceId },
      orderBy: { id: 'asc' },
      select: {
        id: true,
        contentItemId: true,
        version: true,
        body: true,
        contentHash: true,
        locale: true,
        creationMethod: true,
        sourceIds: true,
        createdByUserId: true,
        createdAt: true,
      },
    }),
    db.postVariant.findMany({
      where: { workspaceId: input.workspaceId },
      orderBy: { id: 'asc' },
      select: {
        id: true,
        contentItemId: true,
        contentVersionId: true,
        connectionId: true,
        destinationId: true,
        provider: true,
        locale: true,
        body: true,
        mediaAssetIds: true,
        signatureId: true,
        inheritedFields: true,
        overriddenFields: true,
        state: true,
        capabilitySnapshotVersion: true,
        createdAt: true,
        updatedAt: true,
      },
    }),
    db.socialConnection.findMany({
      where: { workspaceId: input.workspaceId },
      orderBy: { id: 'asc' },
      select: {
        id: true,
        brandId: true,
        provider: true,
        accountType: true,
        displayName: true,
        handle: true,
        avatarUrl: true,
        profileUrl: true,
        status: true,
        statusReason: true,
        grantedScopes: true,
        capabilityVersion: true,
        capabilitiesRefreshedAt: true,
        connectedAt: true,
        disconnectedAt: true,
        createdAt: true,
        updatedAt: true,
      },
    }),
    db.mediaAsset.findMany({
      where: { workspaceId: input.workspaceId },
      orderBy: { id: 'asc' },
      select: {
        id: true,
        brandId: true,
        kind: true,
        mimeType: true,
        byteSize: true,
        checksumSha256: true,
        width: true,
        height: true,
        durationMs: true,
        altText: true,
        rights: true,
        originKind: true,
        originUrl: true,
        scanState: true,
        retentionExpiresAt: true,
        storageDeletedAt: true,
        deletedAt: true,
        createdAt: true,
        updatedAt: true,
      },
    }),
    db.publishJob.findMany({
      where: { workspaceId: input.workspaceId },
      orderBy: { id: 'asc' },
      select: {
        id: true,
        contentItemId: true,
        contentVersionId: true,
        postVariantId: true,
        connectionId: true,
        approvalRequestId: true,
        approvalPolicy: true,
        scheduledFor: true,
        scheduledTimeZone: true,
        state: true,
        attemptCount: true,
        lastErrorClass: true,
        lastErrorCode: true,
        surface: true,
        dispatchedAt: true,
        completedAt: true,
        canceledAt: true,
        createdAt: true,
        updatedAt: true,
      },
    }),
    db.publicationReceipt.findMany({
      where: { workspaceId: input.workspaceId },
      orderBy: { id: 'asc' },
      select: {
        id: true,
        publishJobId: true,
        contentVersionId: true,
        connectionId: true,
        provider: true,
        externalPostId: true,
        permalink: true,
        contentHash: true,
        mediaChecksums: true,
        publishedShortLinks: true,
        publishedAt: true,
        dispatchedAt: true,
        scheduledFor: true,
        scheduledTimeZone: true,
        surface: true,
        approvedByUserId: true,
        approvalPolicy: true,
        costActualMinor: true,
        costCurrency: true,
        deletedExternallyAt: true,
        lastAnalyticsSyncAt: true,
        createdAt: true,
      },
    }),
    db.auditEvent.findMany({
      where: { workspaceId: input.workspaceId },
      orderBy: { id: 'asc' },
      select: {
        id: true,
        actorType: true,
        actorId: true,
        surface: true,
        action: true,
        targetType: true,
        targetId: true,
        beforeHash: true,
        afterHash: true,
        correlationId: true,
        createdAt: true,
      },
    }),
  ]);

  return mapDataExportArchive({
    workspace,
    memberships,
    brands,
    campaigns,
    contentItems,
    versions,
    variants,
    connections,
    media,
    jobs,
    receipts,
    audits,
    exportId: input.exportId,
    generatedAt: input.generatedAt,
  });
}
