import { ROUTES } from '@/features/marketing/site';

import { EDITORIAL_DESK, PLATFORM_DESK } from '../bylines';
import type { BlogArticle } from '../types';

/**
 * Content module, loaded per slug. Each language this article exists in is a
 * key of `content`. See `../types.ts` for why article prose is not in the ICU
 * catalog, and why titles are written per language rather than translated.
 */
export const idempotentSchedulingThroughAnApi: BlogArticle = {
  slug: 'idempotent-scheduling-through-an-api',
  cluster: 'developers',
  author: EDITORIAL_DESK,
  reviewer: PLATFORM_DESK,
  published: '2026-08-10',
  updated: '2026-08-10',
  sources: [
    {
      title: 'Posts API, LinkedIn community management',
      url: 'https://learn.microsoft.com/en-us/linkedin/marketing/community-management/shares/posts-api',
      readOn: '2026-08-10',
    },
    {
      title: 'Instagram Platform content publishing',
      url: 'https://developers.facebook.com/docs/instagram-platform/content-publishing/',
      readOn: '2026-08-10',
    },
    {
      title: 'Using OAuth 2.0 to access Google APIs',
      url: 'https://developers.google.com/identity/protocols/oauth2',
      readOn: '2026-08-10',
    },
  ],
  content: {
    en: {
      title: 'Scheduling through an API without publishing twice',
      description:
        'What an idempotency key has to cover, why a schedule needs an instant and a zone, and how to design a retry that a platform outage cannot turn into a duplicate.',
      blocks: [
        {
          kind: 'paragraph',
          text: 'If you are scheduling posts from your own code, through any publishing API, the interesting failure is never the request that fails cleanly. It is the request whose response you never saw. Somewhere between your timeout and the platform, a post may or may not exist, and the next thing your program does decides whether the account gets one post or two.',
        },
        {
          kind: 'paragraph',
          text: 'This is a short account of what has to be true for that decision to be safe, whether the scheduling API you call is one you bought or one you wrote.',
        },

        {
          kind: 'heading',
          id: 'key',
          text: 'The key has to be yours, and it has to mean one intention',
        },
        {
          kind: 'paragraph',
          text: 'An idempotency key is a value you generate before the first attempt and reuse on every retry of the same intention. Two properties matter more than the format.',
        },
        {
          kind: 'list',
          items: [
            'It is generated by the caller, before the call. A key minted by the server on receipt cannot protect the case where the request arrived and the response did not.',
            'It identifies one intention, not one payload. If a scheduled time is corrected, that is the same intention and the same key. If a second post is written, that is a new intention and a new key, even when the text is identical.',
          ],
        },
        {
          kind: 'paragraph',
          text: 'The second property is where most designs go wrong. Hashing the request body looks tidy and then quietly refuses a legitimate second post that happens to repeat yesterday wording, or accepts a duplicate because a stray whitespace change made a new hash.',
        },
        {
          kind: 'code',
          caption:
            'The shape of a safe retry. The key is minted once, stored with the intention, and reused unchanged.',
          lines: [
            'key = uuid()                       # once, before the first attempt',
            'store(key, intention, status="pending")',
            'response = POST /schedules  Idempotency-Key: key',
            '# timeout, connection reset, process killed:',
            '# retry the same call with the same key, never a new one',
            '# the server returns the original outcome rather than acting again',
          ],
        },

        {
          kind: 'heading',
          id: 'time',
          text: 'A scheduled time is an instant plus a zone, never a local string',
        },
        {
          kind: 'paragraph',
          text: 'A schedule that stores nine in the morning without a zone is not a time. It is a wish that resolves differently on the server, on the client, and again after a daylight saving change.',
        },
        {
          kind: 'paragraph',
          text: 'Send both: the exact instant, and the IANA zone the person meant. The instant makes the schedule unambiguous. The zone is what lets the system answer the question a person will eventually ask, which is whether a post moved because the clocks changed or because somebody edited it. A stored offset cannot answer that, because an offset is a consequence of a zone and a date, not a substitute for either.',
        },
        {
          kind: 'callout',
          title: 'The dangerous hours are the ones that repeat or vanish',
          body: 'On a spring transition a local time can be absent, and on an autumn transition it can occur twice. Any scheduler that treats local time as authoritative will either skip a post or publish it twice on exactly two days a year, and both will be reported as random.',
        },

        {
          kind: 'heading',
          id: 'platform',
          text: 'The platform beneath you offers less than you think',
        },
        {
          kind: 'paragraph',
          text: 'It is tempting to assume the publishing platform will protect you. Read what is actually documented.',
        },
        {
          kind: 'table',
          caption: 'Documented behaviour that shapes a retry',
          columns: ['What the platform documents', 'What your code must therefore own'],
          rows: [
            [
              'LinkedIn states that post deletions are idempotent, returning 204 for a post already deleted',
              'Cleanup can be repeated safely. Creation has no such promise, so publish once is your guarantee to build, not theirs.',
            ],
            [
              'LinkedIn documents a PUBLISH_FAILED state and states that an edit is required to reattempt publishing',
              'A retry loop that resends the same call forever will never clear that state. Detect it and hand it to a person.',
            ],
            [
              'Instagram separates container creation from publishing, and suggests checking a container status roughly once a minute for up to five minutes',
              'Publishing is a small state machine, not a call. Persist which step you reached so a restart resumes rather than restarts.',
            ],
            [
              'Google documents refresh tokens expiring on several conditions, including six months of disuse and revocation by the user',
              'Authentication can fail in the middle of a retry sequence. Distinguish a credential failure from a publishing failure, because only one of them should ever be retried.',
            ],
          ],
        },

        { kind: 'heading', id: 'receipts', text: 'Write the record before the call, not after it' },
        {
          kind: 'paragraph',
          text: 'A record written after a successful call cannot describe the only case that matters. Write the attempt first, with the key, the intention and the target account, then update it with the outcome. If the process dies mid flight, the record is what tells the next run that something might already exist.',
        },
        {
          kind: 'paragraph',
          text: 'Make that record immutable once written. An audit trail that can be edited to look tidy is not an audit trail, and the first time somebody asks whether a post went out twice, the tidy version is worth nothing.',
        },
        {
          kind: 'list',
          items: [
            'The idempotency key, so a retry is recognisable as a retry.',
            'The exact content sent, so a read back against the platform can be conclusive.',
            'The scheduled instant and the zone, so a moved post can be explained.',
            'The platform identifier once there is one, because that is the only proof the post exists.',
            'The final state, including unknown, which is a real state and must be storable.',
          ],
        },

        { kind: 'heading', id: 'testing', text: 'Test the five failures that actually happen' },
        {
          kind: 'list',
          ordered: true,
          items: [
            'The worker dies after the platform accepted the post but before the response was recorded.',
            'The platform times out, and the post turns out to exist.',
            'A webhook or callback is delivered twice for the same publication.',
            'The credential is revoked between scheduling and publication.',
            'A daylight saving transition moves the local time the person chose.',
          ],
        },
        {
          kind: 'paragraph',
          text: 'If those five are not in the test suite, they are in production instead. Each one is cheap to simulate and expensive to meet for the first time on a client account.',
        },
        {
          kind: 'cta',
          label: 'Read the developer documentation',
          href: ROUTES.docs,
        },
      ],
    },
  },
};
