import type { RelayConfig } from '@relay/config';
import type { Logger } from '@relay/observability';

import type { Clock } from '../application/port.js';
import type {
  IdentityProvider,
  IdentitySession,
  SignUpInput,
  TotpEnrollment,
} from '../modules/auth/identity.port.js';

/**
 * Doubles for everything the API is handed at bootstrap.
 *
 * These are hand written rather than generated by a mocking library so the
 * behaviour a test relies on is readable in one file. A mock whose behaviour is
 * assembled across twelve `when(...)` calls is a mock nobody can reason about
 * when the test fails.
 */

/** A clock a test controls completely. Never reads the wall clock. */
export class FakeClock implements Clock {
  private current: Date;

  constructor(start: string = '2026-08-04T09:00:00.000Z') {
    this.current = new globalThis.Date(start);
  }

  now(): Date {
    return new globalThis.Date(this.current.getTime());
  }

  advance(seconds: number): void {
    this.current = new globalThis.Date(this.current.getTime() + seconds * 1000);
  }

  set(instant: string): void {
    this.current = new globalThis.Date(instant);
  }
}

/** A logger that records rather than prints, so assertions can read it. */
export class RecordingLogger {
  readonly lines: { level: string; fields: unknown; message: string }[] = [];

  private record(level: string) {
    return (fields: unknown, message?: unknown): void => {
      this.lines.push({ level, fields, message: typeof message === 'string' ? message : '' });
    };
  }

  readonly trace = this.record('trace');
  readonly debug = this.record('debug');
  readonly info = this.record('info');
  readonly warn = this.record('warn');
  readonly error = this.record('error');
  readonly fatal = this.record('fatal');

  child(): RecordingLogger {
    return this;
  }

  /** Every message logged at or above `level`, for assertions. */
  messages(level?: string): readonly string[] {
    return this.lines
      .filter((line) => level === undefined || line.level === level)
      .map((line) => line.message);
  }
}

export interface FakeIdentityState {
  /** Alias or email, lowercased, to identity. */
  readonly identities: Map<string, { userId: string; email: string; password: string }>;
}

/**
 * An identity provider that answers from memory.
 *
 * It deliberately reproduces the two behaviours the security plan depends on:
 * every failure returns null rather than a reason, and the dummy verification
 * path does the same amount of work as a real one so the timing test has
 * something honest to measure.
 */
export class FakeIdentityProvider implements IdentityProvider {
  readonly signUpCalls: SignUpInput[] = [];
  readonly magicLinks: { email: string; locale: string }[] = [];
  readonly passwordResets: { email: string; locale: string }[] = [];
  readonly signOuts: string[] = [];
  dummyVerifications = 0;
  otpCode = '123456';

  constructor(private readonly state: FakeIdentityState) {}

  private session(userId: string, email: string): IdentitySession {
    return {
      userId,
      email,
      emailVerified: true,
      providerSessionId: `provider-session-${userId}`,
      mfaRequired: false,
      mfaSatisfiedAt: null,
    };
  }

  signUp(input: SignUpInput): Promise<{ userId: string | null }> {
    this.signUpCalls.push(input);
    const existing = this.state.identities.get(input.email.toLowerCase());
    return Promise.resolve({ userId: existing?.userId ?? null });
  }

  signInWithPassword(input: { email: string; password: string }): Promise<IdentitySession | null> {
    const identity = this.state.identities.get(input.email.toLowerCase());
    if (identity === undefined || identity.password !== input.password) {
      return Promise.resolve(null);
    }
    return Promise.resolve(this.session(identity.userId, identity.email));
  }

  verifyDummyCredential(): Promise<void> {
    this.dummyVerifications += 1;
    return Promise.resolve();
  }

  sendMagicLink(input: { email: string; locale: string }): Promise<void> {
    this.magicLinks.push(input);
    return Promise.resolve();
  }

  verifyOtp(input: { email: string; token: string }): Promise<IdentitySession | null> {
    const identity = this.state.identities.get(input.email.toLowerCase());
    if (identity === undefined || input.token !== this.otpCode) {
      return Promise.resolve(null);
    }
    return Promise.resolve(this.session(identity.userId, identity.email));
  }

  sendPasswordReset(input: { email: string; locale: string }): Promise<void> {
    this.passwordResets.push(input);
    return Promise.resolve();
  }

  signOut(providerSessionId: string): Promise<void> {
    this.signOuts.push(providerSessionId);
    return Promise.resolve();
  }

  enrollTotp(): Promise<TotpEnrollment> {
    return Promise.resolve({
      factorId: 'factor_test',
      provisioningUri: 'otpauth://totp/Relay:test?secret=TESTSECRET&issuer=Relay',
    });
  }

  verifyTotp(input: { code: string }): Promise<boolean> {
    return Promise.resolve(input.code === this.otpCode);
  }
}

/** The minimum config the API needs to boot, with no real credential in it. */
export function testConfig(overrides: Partial<RelayConfig> = {}): RelayConfig {
  const base = {
    service: 'api' as const,
    core: {
      nodeEnv: 'test' as const,
      isProduction: false,
      isDevelopment: false,
      isTest: true,
      appUrl: 'https://app.relay.test',
      apiUrl: 'https://api.relay.test',
      logLevel: 'silent' as const,
    },
    database: { url: undefined, directUrl: undefined },
    supabase: {
      url: 'https://supabase.relay.test',
      anonKey: 'test-anon-key',
      serviceRoleKey: 'test-service-role-key',
      jwtSecret: 'test-jwt-secret',
      storageBucket: 'relay-media',
    },
    redis: { url: undefined },
    temporal: {
      address: undefined,
      namespace: 'default',
      taskQueue: 'relay-publishing',
      apiKey: undefined,
    },
    polar: {
      accessToken: undefined,
      // Not a real secret: a fixed string the suite signs its own fixtures with.
      webhookSecret: 'test-polar-webhook-secret',
      server: 'sandbox' as const,
      monthlyProductId: undefined,
      annualProductId: undefined,
      trialDays: 7,
    },
    ai: {
      provider: 'deepseek' as const,
      promptVersion: undefined,
      requestTimeoutMs: 60_000,
      maxMonthlyUsdPerWorkspace: 25,
      deepseek: {
        apiKey: undefined,
        baseUrl: 'https://api.deepseek.com',
        model: 'deepseek-v4-flash',
      },
    },
    encryption: { kmsKeyId: undefined, localKey: undefined },
    oauth: {
      issuerUrl: 'https://api.relay.test',
      signingKmsKeyId: undefined,
      // Local-only pepper for credential digests in the suite.
      signingLocalKey: 'dGVzdC1zaWduaW5nLWtleS10ZXN0LXNpZ25pbmcta2V5LTEyMzQ=',
    },
    shortLinks: { baseUrl: undefined, hashKey: undefined },
    email: { apiKey: undefined, from: undefined },
    observability: {
      sentryDsn: undefined,
      posthogKey: undefined,
      otelExporterOtlpEndpoint: undefined,
    },
    providers: {
      x: { clientId: undefined, clientSecret: undefined },
      linkedin: { clientId: undefined, clientSecret: undefined },
      meta: { appId: undefined, appSecret: undefined },
      google: { clientId: undefined, clientSecret: undefined },
      tiktok: { clientKey: undefined, clientSecret: undefined },
      bluesky: { serviceUrl: 'https://bsky.social' },
    },
    presentKeys: [],
  };
  return { ...base, ...overrides };
}

/** A logger the API accepts, backed by the recorder above. */
export function asLogger(recorder: RecordingLogger): Logger {
  const candidate: unknown = recorder;
  if (!isLogger(candidate)) {
    throw new Error('RecordingLogger no longer satisfies the Logger interface.');
  }
  return candidate;
}

function isLogger(value: unknown): value is Logger {
  if (typeof value !== 'object' || value === null) {
    return false;
  }
  const methods = ['trace', 'debug', 'info', 'warn', 'error', 'fatal', 'child'];
  // Read through the prototype chain. `child` is a class method, so it is not an
  // own enumerable property and Object.entries would not see it.
  const record = value as Record<string, unknown>;
  return methods.every((name) => typeof record[name] === 'function');
}
