import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import { X } from 'lucide-react';
import { CORE_PROVIDER_IDS, type CoreProviderId } from '@relay/contracts';
import { cn } from '@relay/design-system/utils';
import type { Translator } from '@relay/i18n/translate';

import { StaggerList } from '@/components/motion';
import { HeroDemoSection } from '@/features/demo/hero-demo-section';
import { buildSnippet } from '@/features/developer/lib/setup-snippets';
import { JsonLd } from '@/features/marketing/components/json-ld';
import {
  AgentToolLedger,
  ClosingCta,
  EditorialBigNumber,
  EditorialCard,
  EditorialDisplay,
  EditorialSection,
  EditorialVariantScene,
  Eyebrow,
  ProviderGrid,
  ProviderLogoRow,
  TierGrid,
} from '@/features/marketing/components/editorial';
import { tierColumns } from '@/features/marketing/components/editorial/tier-columns';
import { ColorBand, Sticker } from '@/features/marketing/components/scene';
import {
  Body,
  Fact,
  FactList,
  Heading,
  Lede,
  Step,
  Steps,
  Subheading,
} from '@/features/marketing/components/layout';
import { Cta, TextLink } from '@/features/marketing/components/links';
import { AGENT_TOOL_COUNT, AGENT_TOOL_TIERS } from '@/features/marketing/data/agent-tools';
import { marketingTranslator } from '@/features/marketing/i18n';
import { offerJsonLd, pageMetadata } from '@/features/marketing/seo';
import { ROUTES } from '@/features/marketing/site';

export async function generateMetadata({
  params,
}: {
  readonly params: Promise<{ readonly locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  return pageMetadata('web.meta.home.title', 'web.meta.home.description', ROUTES.home, locale);
}

const EXAMPLE_ROWS = [
  {
    id: 'x',
    accountKey: 'web.home.example.x.account',
    variantKey: 'web.home.example.x.variant',
    checkKey: 'web.home.example.x.check',
  },
  {
    id: 'linkedin',
    accountKey: 'web.home.example.linkedin.account',
    variantKey: 'web.home.example.linkedin.variant',
    checkKey: 'web.home.example.linkedin.check',
  },
  {
    id: 'instagram',
    accountKey: 'web.home.example.instagram.account',
    variantKey: 'web.home.example.instagram.variant',
    checkKey: 'web.home.example.instagram.check',
  },
  {
    id: 'youtube',
    accountKey: 'web.home.example.youtube.account',
    variantKey: 'web.home.example.youtube.variant',
    checkKey: 'web.home.example.youtube.check',
  },
  {
    id: 'bluesky',
    accountKey: 'web.home.example.bluesky.account',
    variantKey: 'web.home.example.bluesky.variant',
    checkKey: 'web.home.example.bluesky.check',
  },
] as const;

/**
 * The launch cohort: the hero logo row, the "official APIs only" grid and the
 * connector-count sticker.
 *
 * Derived from `CORE_PROVIDER_IDS` rather than typed out. This list used to be
 * eight hand-written ids under a comment claiming it was "every real, shipped
 * connector", which it was not: the cohort in `@relay/contracts` already held
 * ten, so the home page quietly promised a smaller product than the
 * integrations page and the connect dialog did. Deriving it means the page
 * cannot disagree with the cohort again, in either direction — a provider
 * added to or removed from the cohort moves this row with it, on the same
 * commit, with no second edit to remember.
 *
 * The type is `CoreProviderId`, not `ProviderId`: `ProviderLogoRow` holds a
 * total record of marks over the cohort, so a provider joining
 * `CORE_PROVIDER_IDS` without a mark fails to compile rather than rendering a
 * gap in the first thing on the page.
 *
 * `features/marketing/data/connectors.ts` (the capability matrix) derives from
 * the same constant, so the two public connector surfaces are two views of one
 * list.
 */
const CONNECTOR_PROVIDERS: readonly CoreProviderId[] = CORE_PROVIDER_IDS;

/**
 * The MCP clients Relay ships a reviewed setup for, named the way the product
 * itself names them (`SETUP_CLIENTS` in `features/developer/lib/
 * setup-snippets.ts`, which is what the in-product setup panel renders).
 *
 * `buzz` is omitted: it is a workflow runner calling the REST API, not an MCP
 * client, and this row is specifically about what speaks MCP. `cli` is omitted
 * because the CLI has its own row further down the page.
 */
const AGENT_CLIENT_KEYS = [
  'developer.setup.claudeCode',
  'developer.setup.codex',
  'developer.setup.hermes',
  'developer.setup.genericMcp',
] as const;

/**
 * The Claude Code configuration, generated by the same function the signed-in
 * developer portal generates it with. It is not retyped here, so this block
 * cannot drift from the block a customer actually copies.
 *
 * `relay.example` is the RFC 2606 example domain, and the credential is the
 * environment-variable placeholder the real snippet uses. Nothing here is a
 * live endpoint or a secret.
 */
const CLAUDE_CODE_SNIPPET = buildSnippet('claude-code', {
  mcpEndpoint: 'https://mcp.relay.example/mcp',
  apiBaseUrl: 'https://api.relay.example',
  serviceAccountName: 'relay-agent',
});

const CONNECT_STEPS = [
  {
    id: 'credential',
    titleKey: 'web.home.v2.agents.connect.step.credential.title',
    bodyKey: 'web.home.v2.agents.connect.step.credential.body',
  },
  {
    id: 'authorize',
    titleKey: 'web.home.v2.agents.connect.step.authorize.title',
    bodyKey: 'web.home.v2.agents.connect.step.authorize.body',
  },
  {
    id: 'work',
    titleKey: 'web.home.v2.agents.connect.step.work.title',
    bodyKey: 'web.home.v2.agents.connect.step.work.body',
  },
] as const;

const PILLARS = [
  {
    id: 'confidence',
    titleKey: 'web.home.pillars.confidence.title',
    bodyKey: 'web.home.pillars.confidence.body',
    proofKey: 'web.home.pillars.confidence.proof',
  },
  {
    id: 'adapt',
    titleKey: 'web.home.pillars.adapt.title',
    bodyKey: 'web.home.pillars.adapt.body',
    proofKey: 'web.home.pillars.adapt.proof',
  },
  {
    id: 'loop',
    titleKey: 'web.home.pillars.loop.title',
    bodyKey: 'web.home.pillars.loop.body',
    proofKey: 'web.home.pillars.loop.proof',
  },
  {
    id: 'anywhere',
    titleKey: 'web.home.pillars.anywhere.title',
    bodyKey: 'web.home.pillars.anywhere.body',
    proofKey: 'web.home.pillars.anywhere.proof',
  },
  {
    id: 'economics',
    titleKey: 'web.home.pillars.economics.title',
    bodyKey: 'web.home.pillars.economics.body',
    proofKey: 'web.home.pillars.economics.proof',
  },
] as const;

const SURFACES = [
  { id: 'web', nameKey: 'web.home.surfaces.web', bodyKey: 'web.home.surfaces.webBody' },
  { id: 'mcp', nameKey: 'web.home.surfaces.mcp', bodyKey: 'web.home.surfaces.mcpBody' },
  { id: 'api', nameKey: 'web.home.surfaces.api', bodyKey: 'web.home.surfaces.apiBody' },
  { id: 'cli', nameKey: 'web.home.surfaces.cli', bodyKey: 'web.home.surfaces.cliBody' },
  {
    id: 'webhooks',
    nameKey: 'web.home.surfaces.webhooks',
    bodyKey: 'web.home.surfaces.webhooksBody',
  },
] as const;

const BOUNDARIES = [
  'web.home.honest.noMedia',
  'web.home.honest.noAutomationOfEngagement',
  'web.home.honest.noUnofficial',
  'web.home.honest.noPromises',
  'web.home.honest.noUnattendedPublishing',
] as const;

type Pillar = (typeof PILLARS)[number];

/**
 * One proof row.
 *
 * These rows used to open with a display-scale `01` / `02` / `03`. The
 * numerals are gone: nothing about "publish with confidence" is the first step
 * of anything, so the sequence was decoration wearing the clothes of
 * information, and a reader who scanned it learned only that there were five
 * of something. What is left is the editorial split the rest of the site uses
 * — the claim in the narrow column, the argument and its proof in the wide one.
 *
 * The marigold rule survives the numeral because it was never the numeral's:
 * it is the row's own mark, and it grows from the row's hover/focus state. It
 * is a CSS transform, so the global 1ms reduced-motion override reaches it,
 * there is no GSAP timeline to branch on `useMotionOk`, and nothing is hidden
 * in server HTML.
 */
function PillarRow({ pillar, t }: { readonly pillar: Pillar; readonly t: Translator }): ReactNode {
  return (
    <div
      data-stagger-item
      className="border-border-subtle group grid gap-4 border-b py-10 lg:grid-cols-12 lg:items-start lg:gap-12"
    >
      <div className="lg:col-span-4">
        <span
          aria-hidden="true"
          className={cn(
            'bg-accent-warm mb-4 block h-1 w-14 origin-[left_center] rounded-xs rtl:origin-[right_center]',
            'scale-x-50 transition-transform duration-(--duration-expressive) ease-(--ease-out-expo)',
            'group-focus-within:scale-x-100 group-hover:scale-x-100',
          )}
        />
        <h3 className="text-title-lg text-text-primary text-pretty">{t.format(pillar.titleKey)}</h3>
      </div>
      <div className="space-y-4 lg:col-span-8">
        <p className="text-body-lg text-text-secondary max-w-[68ch] leading-[1.65]">
          {t.format(pillar.bodyKey)}
        </p>
        <p className="border-border-default text-body-sm text-text-tertiary border-s ps-4 font-mono leading-[1.6]">
          {t.format(pillar.proofKey)}
        </p>
      </div>
    </div>
  );
}

export default async function HomePage({
  params,
}: {
  readonly params: Promise<{ readonly locale: string }>;
}): Promise<ReactNode> {
  const { locale } = await params;
  const t = await marketingTranslator(locale);

  const providerName = (provider: CoreProviderId): string => t.format(`web.provider.${provider}`);

  const variantRows = EXAMPLE_ROWS.map((row) => ({
    id: row.id,
    provider: row.id,
    account: t.format(row.accountKey),
    variant: t.format(row.variantKey),
    check: t.format(row.checkKey),
  }));

  const toolTiers = AGENT_TOOL_TIERS.map((tier) => ({
    risk: tier.risk,
    label: t.format(`web.home.v2.agents.tier.${tier.risk}.label`),
    rule: t.format(`web.home.v2.agents.tier.${tier.risk}.rule`),
    count: t.format('web.home.v2.agents.tier.count', { count: tier.tools.length }),
    tools: tier.tools,
  }));

  return (
    <>
      {/*
        1. The hero, in the order a stranger reads it.

        Platforms, promise, how it works, one action. The row of marks comes
        first because it is the fastest fact on the page: before a word is
        read, the reader knows which networks this publishes to. Then a six
        word headline, then the sentence that names the clients and the
        surfaces, then one vermilion action and one quiet one.

        What used to be here: an eyebrow, then a twenty word literary sentence
        set at display size that filled a 900px viewport on its own, then a
        platform cycler, then a lede, then two equally weighted buttons. The
        eyebrow is gone because the craft floor bans it and the headline
        carries its own weight. The long sentence is not deleted — it is
        `web.home.promise`, still translated in every locale, and it still runs
        further down the page where a paragraph is what a reader wants.

        The `<h1>` stays the LCP element with its finished text in server HTML.
        `EditorialDisplay size="sm"` caps it at 3.75rem, which keeps the
        headline, the subhead and the actions inside 900px of viewport height
        with the demonstration below the fold rather than beside it.
      */}
      <EditorialSection reveal={false} containerClassName="py-14 md:py-20 lg:py-24">
        {/*
          The row runs the full measure of the page rather than the width of
          the headline column: at desktop widths the whole cohort then reads as
          one strip in a single pass, which is the entire point of putting it
          first. It wraps to two or three lines on a phone, which is fine — it
          still resolves before the headline does.
        */}
        <ProviderLogoRow
          providers={CONNECTOR_PROVIDERS}
          ariaLabel={t.t('web.home.v2.hero.providersLabel')}
          name={providerName}
        />

        <div className="mt-9 max-w-[52rem]">
          <EditorialDisplay as="h1" size="sm" reveal>
            {t.t('web.home.v2.hero.headline')}
          </EditorialDisplay>

          <Lede className="mt-6 max-w-[64ch]">{t.t('web.home.v2.hero.subhead')}</Lede>

          <div className="mt-9 flex flex-wrap items-center gap-3">
            <Cta href={ROUTES.signUp}>{t.t('web.cta.startTrial')}</Cta>
            <Cta href="#agents" variant="secondary">
              {t.t('web.home.v2.hero.agentsCta')}
            </Cta>
          </div>

          <p className="text-body-sm text-text-tertiary mt-5">
            {t.t('web.home.v2.sticker.trial')}
          </p>
        </div>
      </EditorialSection>

      {/*
        2. The agent story, which this site has never told.

        It is the strongest thing we have and it was invisible: a real remote
        MCP server, a real CLI, a real REST API and real signed webhooks, all
        in front of the same application services, mentioned nowhere above the
        fold and nowhere at all as a story.

        Deliberately not three icon-and-heading cards. The ladder from read to
        consequential is the whole idea, and equal boxes would flatten it: the
        section reads connect, then what an agent may call, then what it may
        never do without a person.

        The tinted band is the page's first of its two budgeted `ColorBand`s
        (`scene/scene-budget.test.ts`). Ultramarine, because the vermilion is
        spent on the action in the hero and a section-wide vermilion would
        compete with it.
      */}
      <ColorBand accent="cool" id="agents" texture>
        <div className="max-w-[46rem]">
          <Heading>{t.t('web.home.v2.agents.title')}</Heading>
          <Lede className="mt-5">{t.t('web.home.v2.agents.lede')}</Lede>
        </div>

        <div className="mt-14 grid gap-12 lg:grid-cols-[minmax(0,1fr)_minmax(0,30rem)] lg:gap-14">
          <div>
            <Subheading as="h3">{t.t('web.home.v2.agents.connect.title')}</Subheading>
            {/*
              Numbered, and allowed to be: you cannot authorize a client you
              have not pointed anywhere, and an agent cannot read accounts
              before the grant exists. The craft floor bans section numbers
              whose sequence carries nothing — which is why the proof rows
              further down lost theirs — not an ordered list that is actually
              ordered.
            */}
            <Steps>
              {CONNECT_STEPS.map((step, index) => (
                <Step key={step.id} index={index + 1} title={t.format(step.titleKey)}>
                  {t.format(step.bodyKey)}
                </Step>
              ))}
            </Steps>
          </div>

          <div className="min-w-0">
            {/*
              The configuration a customer actually copies, generated by the
              product's own snippet builder rather than retyped. The block
              scrolls inside its own container so a long endpoint never makes
              the page scroll sideways.
            */}
            <EditorialCard tone="sunken" interactive={false} flush>
              <pre className="text-mono relay-scroll-x px-4 py-5 font-mono leading-[1.8]">
                <code>{CLAUDE_CODE_SNIPPET}</code>
              </pre>
            </EditorialCard>
            <p className="text-body-sm text-text-tertiary mt-3">
              {t.t('web.home.v2.agents.connect.snippetCaption')}
            </p>

            <p className="text-body-sm text-text-secondary mt-8">
              {t.t('web.home.v2.agents.connect.clients')}
            </p>
            <ul className="mt-3 flex flex-wrap gap-2">
              {AGENT_CLIENT_KEYS.map((key) => (
                <li
                  key={key}
                  className="border-border-strong text-body-sm text-text-primary rounded-sm border px-2.5 py-1"
                >
                  {t.format(key)}
                </li>
              ))}
            </ul>
            <p className="text-body-sm text-text-tertiary mt-3 max-w-[46ch] leading-[1.6]">
              {t.t('web.home.v2.agents.connect.clientsNote')}
            </p>
          </div>
        </div>

        <div className="mt-16">
          <Subheading as="h3">
            {t.format('web.home.v2.agents.tools.title', { count: AGENT_TOOL_COUNT })}
          </Subheading>
          <Body className="mt-3">{t.t('web.home.v2.agents.tools.body')}</Body>
          <AgentToolLedger tiers={toolTiers} className="mt-8" />
        </div>

        {/*
          The confirmation step gets its own moment rather than a fourth ledger
          row: it is the one guarantee that makes an agent with publish rights
          safe to give to a stranger, and it is not a tool, it is what happens
          instead of one.
        */}
        <div className="mt-12 max-w-[52rem]">
          <EditorialCard interactive={false}>
            <Subheading as="h3" className="text-title-sm">
              {t.t('web.home.v2.agents.confirm.title')}
            </Subheading>
            <p className="text-body-lg text-text-secondary mt-3 leading-[1.65]">
              {t.t('web.home.v2.agents.confirm.body')}
            </p>
          </EditorialCard>
        </div>

        <p className="mt-10">
          <TextLink href={ROUTES.docs}>{t.t('web.home.v2.agents.docsCta')}</TextLink>
        </p>
      </ColorBand>

      {/* 3. The same five surfaces, as rows rather than as five identical cards. */}
      <EditorialSection rule id="surfaces" reveal={false}>
        <Heading className="max-w-[24ch]">{t.t('web.home.surfaces.title')}</Heading>
        <Body className="mt-4">{t.t('web.home.surfaces.body')}</Body>

        <EditorialBigNumber
          value={SURFACES.length}
          locale={locale}
          label={t.t('web.home.v2.surfacesStat')}
          className="mt-12 mb-10"
        />

        <FactList>
          {SURFACES.map((surface) => (
            <Fact key={surface.id} term={t.format(surface.nameKey)}>
              {t.format(surface.bodyKey)}
            </Fact>
          ))}
        </FactList>

        <p className="mt-10">
          <TextLink href={ROUTES.developers}>{t.t('nav.public.forDevelopers')}</TextLink>
        </p>
      </EditorialSection>

      {/*
        4. The demonstration. It used to sit beside the headline, where it
        halved the width of the promise and pushed the action off a 900px
        screen. Below the fold it can be the size it deserves, and the hero can
        be read in one glance.
      */}
      <EditorialSection rule id="demo" reveal={false} ariaLabel={t.t('web.demo.hero.more')}>
        {/*
          `web.home.lede` is the sentence the hero used to carry under the
          promise. It is not deleted and not orphaned: it says what the product
          is, and the place for that is immediately before the walkthrough that
          shows it, not in front of the headline that has already said it in
          six words.
        */}
        <Lede className="mb-10">{t.t('web.home.lede')}</Lede>
        <HeroDemoSection locale={locale} />
        <p className="mt-6">
          <TextLink href={ROUTES.demo}>{t.t('web.demo.hero.more')}</TextLink>
        </p>
      </EditorialSection>

      {/*
        5. The connectors, still.

        The looping marquee that used to run above this grid is gone. The hero
        now names every platform in its own colours at logo scale, so a
        scrolling track of the same ten names was the third rendering of one
        list, and it was the one that could never be read in full. The grid is
        what a crawler, a no-JS client and a reduced-motion visitor were
        getting anyway.
      */}
      <EditorialSection rule id="connectors" ariaLabel={t.t('web.home.v2.marqueeCaption')}>
        <Eyebrow>{t.t('web.home.v2.marqueeCaption')}</Eyebrow>
        <ProviderGrid providers={CONNECTOR_PROVIDERS} className="mt-8" />
        <div className="mt-8">
          <Sticker
            fact={t.format('web.home.b3.sticker.connectorsFact', {
              count: CONNECTOR_PROVIDERS.length,
            })}
            source={t.format('web.home.b3.sticker.connectorsSource')}
            accent="cool"
          />
        </div>
      </EditorialSection>

      {/* 6. One idea, a platform-native version each. The core proof. */}
      <EditorialSection rule id="example" reveal={false}>
        <Heading className="max-w-[32ch]">{t.t('web.home.example.title')}</Heading>
        <Body className="mt-4">{t.t('web.home.example.body')}</Body>
        <EditorialVariantScene
          rows={variantRows}
          masterLabel={t.t('web.home.v2.variantScene.masterLabel')}
          className="mt-12"
        />
      </EditorialSection>

      {/*
        7. The five proof pillars, and the long promise the hero used to set at
        display size. It reads as a standfirst here, which is what it always
        was.
      */}
      <EditorialSection rule id="pillars" reveal={false}>
        <Heading className="max-w-[28ch]">{t.t('web.home.pillars.title')}</Heading>
        <Lede className="mt-5">{t.t('web.home.promise')}</Lede>
        <StaggerList stagger={0.07} className="border-border-default mt-12 border-t">
          {PILLARS.map((pillar) => (
            <PillarRow key={pillar.id} pillar={pillar} t={t} />
          ))}
        </StaggerList>
      </EditorialSection>

      {/*
        8. The boundaries. The copy is unchanged and stays a quiet disclosure
        rather than a hero moment: this is a sales page for what the product
        does, and four screens of "No ..." set in display type reads as
        apologetic.
      */}
      <EditorialSection rule id="boundaries">
        <Heading as="h2">{t.t('web.home.honest.title')}</Heading>
        <p className="text-body-md text-text-secondary mt-3 max-w-[62ch]">
          {t.t('web.home.honest.lede')}
        </p>
        <ul className="mt-8 grid gap-x-10 gap-y-3 sm:grid-cols-2">
          {BOUNDARIES.map((key) => (
            <li key={key} className="flex items-start gap-2.5">
              <X aria-hidden="true" className="text-text-tertiary mt-0.5 size-4 shrink-0" />
              <p className="text-body-sm text-text-secondary leading-[1.5] text-pretty">
                {t.format(key)}
              </p>
            </li>
          ))}
        </ul>
        <p className="mt-8">
          <TextLink href={ROUTES.changelog}>{t.t('nav.public.changelog')}</TextLink>
        </p>
      </EditorialSection>

      {/* 9. Pricing teaser. Both figures shown here are already stated,
          verbatim, in `billing.plan.monthlyPrice` / `billing.plan.single`. */}
      <EditorialSection rule id="pricing-teaser">
        <Heading className="max-w-[24ch]">{t.t('web.home.v2.pricingTeaser.title')}</Heading>
        {/* The plain-language version of the ladder below it: one price, what
            it covers, and that the trial needs no card. It used to sit under
            the hero, where a stranger met a dollar figure before they knew
            what the product was. */}
        <Body className="mt-4">{t.t('web.home.summaryLine')}</Body>
        {/* The three sizes, compact: the same integer minor units and the
            same interval control as the pricing page, without the delta
            prose. A visitor who never reaches /pricing should still know the
            ladder exists and that only Standard is on sale. */}
        <TierGrid
          locale={locale}
          variant="compact"
          tiers={tierColumns({
            t,
            ctaHref: ROUTES.signUp,
            ctaLabel: t.t('web.cta.startTrial'),
          })}
          intervalGroupLabel={t.t('web.pricing.tierGrid.intervalGroup')}
          monthlyLabel={t.t('web.pricing.monthlyLabel')}
          annualLabel={t.t('web.pricing.annualLabel')}
          startHereLabel={t.t('web.pricing.tierGrid.startHere')}
          className="mt-12"
        />

        {/* One presentation of the ladder on this page, not two. This card used
            to repeat the Standard column's own two numbers a second time,
            directly beneath the TierGrid that already states them — the exact
            "two prices for one plan" confusion the pricing page itself was
            rebuilt to remove. The trial note and the link to the full page
            are the part worth keeping; the numbers are not, because the grid
            above already carries them. */}
        <p className="text-body-md text-text-secondary mt-8 max-w-sm">
          {t.t('web.home.v2.sticker.trial')}
        </p>
        <p className="mt-4">
          <TextLink href={ROUTES.pricing} className="text-body-md">
            {t.t('web.cta.seePricing')}
          </TextLink>
        </p>
      </EditorialSection>

      {/* 10. Closing. The page's one inverted band. */}
      <ClosingCta
        id="start"
        title={t.t('web.home.closing.title')}
        body={t.t('web.home.closing.body')}
        cta={{ href: ROUTES.signUp, label: t.t('web.cta.startTrial') }}
        footnote={t.t('web.cta.trialFootnote')}
      />

      <JsonLd node={await offerJsonLd(locale)} />
    </>
  );
}
