export const settingsMessages = {
  'settings.title': '設定', 'settings.saved': '已儲存', 'settings.unsavedChanges': '你有未儲存的變更。',
  'settings.workspace.title': 'Workspace', 'settings.workspace.name': 'Workspace 名稱', 'settings.workspace.defaultTimeZone': '預設時區', 'settings.workspace.defaultLocale': '預設介面語言', 'settings.workspace.defaultContentLocale': '預設內容語言', 'settings.workspace.transferOwnership': '轉移擁有權', 'settings.workspace.delete': '刪除 Workspace', 'settings.workspace.deleteWarning': '刪除 Workspace 會取消排程貼文、撤銷連線並移除已儲存媒體。收據會依條款所述保留期間保存。',
  'settings.members.title': '成員與角色', 'settings.members.invite': '邀請人員', 'settings.members.inviteEmail': '電子郵件地址', 'settings.members.inviteSent': '已傳送邀請至 {email}。', 'settings.members.pending': '已邀請，尚未接受', 'settings.members.count': '{count, plural, other {# 位成員}}', 'settings.members.removeConfirm': '將 {name} 從此 Workspace 移除？其過去操作會保留在稽核記錄中。', 'settings.role.owner.label': '擁有者', 'settings.role.admin.label': '管理員', 'settings.role.manager.label': '管理者', 'settings.role.editor.label': '編輯者', 'settings.role.approver.label': '核准者', 'settings.role.analyst.label': '分析人員', 'settings.role.viewer.label': '檢視者', 'settings.role.owner.description': '所有功能，包括帳務、安全性和刪除。', 'settings.role.admin.description': '除帳務與刪除 Workspace 外的所有功能。', 'settings.role.manager.description': '管理 Brand、連線、排程及規則。', 'settings.role.editor.description': '建立及編輯內容，請求核准。', 'settings.role.approver.description': '核准或拒絕內容，並排程已核准內容。', 'settings.role.analyst.description': '讀取分析資料與收據。', 'settings.role.viewer.description': '唯讀。', 'settings.role.scopeLabel': '限制為 Brand 與帳號', 'settings.role.mfaRequired': '擁有者必須使用雙重要素驗證。',
  'settings.brands.title': 'Brand', 'settings.brands.add': '新增 Brand', 'settings.brands.voice': '語氣', 'settings.brands.audience': '受眾', 'settings.brands.approvedClaims': '已核准聲明', 'settings.brands.blockedTerms': '封鎖詞彙', 'settings.brands.disclosureDefaults': '預設揭露', 'settings.brands.domains': '網域', 'settings.brands.glossary.title': '詞彙表', 'settings.brands.glossary.term': '術語', 'settings.brands.glossary.preferred': '偏好的翻譯', 'settings.brands.glossary.prohibited': '請勿翻譯為', 'settings.brands.glossary.context': '情境', 'settings.brands.glossary.keepUntranslated': '保持不翻譯', 'settings.brands.localeRules.title': '地區設定規則', 'settings.brands.localeRules.formality': '正式程度', 'settings.brands.localeRules.pronouns': '代名詞與敬稱', 'settings.brands.localeRules.idioms': '避免的慣用語', 'settings.brands.localeRules.emoji': '表情符號和雜湊標籤規範', 'settings.brands.localeRules.legal': '地區法律揭露', 'settings.brands.localeRules.cta': '依市場的行動呼籲', 'settings.brands.localeRules.reviewedExamples': '由母語審閱者核准的範例',
  'settings.sets.title': '集合', 'settings.sets.description': '可重複使用的目標、變體、設定、留言和延遲群組。套用集合會建立獨立草稿。', 'settings.sets.editNote': '編輯集合不會變更已核准或已排程的貼文。', 'settings.signatures.title': '簽名', 'settings.signatures.description': '依 Brand、平台和語言設定範圍的結尾文字、雜湊標籤、連結或揭露。', 'settings.signatures.autoApply': '情境相符時自動加入',
  'settings.localization.title': '本地化', 'settings.localization.interfaceLocale': '介面語言', 'settings.localization.interfaceLocaleHelp': '此應用程式為你顯示的語言。它不會變更貼文的語言。', 'settings.localization.contentLocales': '內容語言', 'settings.localization.contentLocalesHelp': '你發布使用的語言。每個 Brand 都可以依語言設定規則和詞彙表。', 'settings.localization.marketLocales': '受眾市場', 'settings.localization.beta': '測試版翻譯', 'settings.localization.betaHelp': '此語言由機器協助，尚未完全經人工審查。未翻譯文字會回退為英文。', 'settings.localization.humanReviewed': '已由母語人士審查', 'settings.localization.timeZone': '時區', 'settings.localization.weekStart': '每週第一天', 'settings.localization.hourCycle.label': '時間格式', 'settings.localization.hourCycle.h12': '12 小時制', 'settings.localization.hourCycle.h23': '24 小時制',
  'settings.notifications.title': '通知', 'settings.notifications.email': '電子郵件', 'settings.notifications.inApp': '應用程式內', 'settings.notifications.approvalRequests': '核准請求', 'settings.notifications.publishResults': '發布結果', 'settings.notifications.connectionHealth': '連線健康狀態', 'settings.notifications.ruleFailures': '自動化失敗', 'settings.notifications.weeklySummary': '每週摘要', 'settings.notifications.digestOnly': '將這些合併為每日一則訊息',
  'settings.security.title': '安全性', 'settings.security.mfa': '雙重要素驗證', 'settings.security.mfaEnable': '開啟雙重要素驗證', 'settings.security.mfaRequiredFor': '帳務變更、服務帳號、重新連線帳號及撤銷認證資料時必須使用。', 'settings.security.passkeys': '通行密鑰', 'settings.security.sessions': '啟用中的工作階段', 'settings.security.sessionRevoke': '登出此工作階段', 'settings.security.auditLog.title': '稽核記錄', 'settings.security.auditLog.description': '每項操作、執行者或執行項目，以及時間。擁有者和管理員可匯出。', 'settings.security.killSwitch': '緊急停止', 'settings.security.killSwitchBody': '立即停止此 Workspace 的每個排程發布及自動化。沒有內容會被刪除。你可以再次關閉它。', 'settings.security.killSwitchActive': '緊急停止已開啟。沒有貼文會發布。',
  'settings.data.title': '資料控制', 'settings.data.export': '匯出你的資料', 'settings.data.exportPreparing': '正在準備匯出。準備好時會以電子郵件通知你。', 'settings.data.deletionRequest': '請求刪除', 'settings.data.deletionExplain': '刪除會取消排程工作流程、撤銷提供者存取權、移除已儲存媒體，並在提供者要求時將分析資料設為墓碑。', 'settings.data.retention': '保留', 'settings.data.consents': '同意', 'settings.data.consent.productAnalytics': '產品分析', 'settings.data.consent.diagnostics': '與支援團隊分享診斷資料', 'settings.data.consent.aiImprovement': '使用我的內容改善助理。除非你開啟，否則此功能為關閉。', 'settings.data.consent.marketingEmail': '以電子郵件傳送產品新聞',
} as const;
