import {
  BUILT_IN_PROVIDERS,
  ProviderHttpClient,
  authorizationDefinitionSchema,
  connectorVaultFromHandles,
  createAuthorizationUrl,
  createConnectorRegistry,
  registerBuiltInProviders,
  type BuiltInProvider,
  type ConnectorLogger,
  type AuthorizationDefinition,
  type ConnectorFeature,
  type SocialConnector,
} from '@relay/connectors';
import {
  detectCapabilities,
  verifiedConnectorsForEnvironment,
  type RelayConfig,
} from '@relay/config';
import {
  ERROR_CODES,
  RelayError,
  type CapabilitySnapshot,
  type CapabilitySupport,
  type ProviderId,
} from '@relay/contracts';
import type { Clock, ConnectorRegistry as ApplicationConnectorRegistry } from '@relay/application';
import type { Logger } from '@relay/observability';

interface OAuthUrlInput {
  readonly definition: AuthorizationDefinition;
  readonly clientId: string;
  readonly state: string;
  readonly codeChallenge: string;
  readonly codeChallengeMethod: 'S256';
  readonly redirectUri: string;
}

/**
 * The verification allow list is expressed over every known provider id, and a
 * provider id can exist before its adapter does. Google Business Profile is in
 * that state today: it is part of the launch cohort but has no adapter, so it is
 * not a built-in provider and cannot be registered. Narrowing here states that
 * rule explicitly rather than leaving it to the registration loop to ignore an
 * id it has no factory for.
 */
function builtInVerifiedProviders(config: RelayConfig): readonly BuiltInProvider[] {
  const builtIn = new Set<string>(BUILT_IN_PROVIDERS);
  return verifiedConnectorsForEnvironment(config).filter(
    (provider): provider is BuiltInProvider => builtIn.has(provider),
  );
}

function assertOAuthInput(input: OAuthUrlInput): void {
  if (input.codeChallengeMethod !== 'S256') {
    throw new RelayError(ERROR_CODES.VALIDATION_FAILED, {
      messageKey: 'error.request_invalid.message',
      details: { reason: 'oauth_code_challenge_method_invalid' },
    });
  }
}

function oauthClientId(config: RelayConfig, provider: ProviderId): string | undefined {
  switch (provider) {
    case 'x':
      return config.providers.x.clientId;
    case 'linkedin':
      return config.providers.linkedin.clientId;
    case 'instagram':
    case 'facebook':
    case 'threads':
      return config.providers.meta.appId;
    case 'youtube':
      return config.providers.google.clientId;
    case 'tiktok':
      return config.providers.tiktok.clientKey;
    case 'mastodon':
      return config.providers.mastodon.clientId;
    case 'reddit':
      return config.providers.reddit.clientId;
    case 'wordpress':
      return config.providers.wordpress.clientId;
    case 'medium':
      return config.providers.medium.clientId;
    case 'pinterest':
      return config.providers.pinterest.clientId;
    case 'slack':
      return config.providers.slack.clientId;
    case 'bluesky':
    case 'telegram':
    case 'devto':
    case 'discord':
    case 'fake':
      return undefined;
  }
}

/**
 * Build an official provider authorization URL while retaining the state and
 * PKCE challenge generated by the application service. The shared connector
 * helper's random state and verifier are intentionally not used here because
 * the application owns the callback transaction and stores the verifier
 * separately. Keeping URL construction local also guarantees that there is
 * exactly one state/verifier pair for a connect attempt.
 */
export function buildVerifiedOAuthAuthorizationUrl(input: OAuthUrlInput): {
  readonly authorizationUrl: string;
  readonly requestedScopes: readonly string[];
} {
  if (input.definition.flavor !== 'oauth2_pkce') {
    throw new RelayError(ERROR_CODES.CAPABILITY_NOT_IMPLEMENTED, {
      messageKey: 'errors.capability_not_implemented',
      details: { reason: 'oauth_flavor_not_supported', capability: 'oauth_start' },
    });
  }
  assertOAuthInput(input);
  const authorization = createAuthorizationUrl({
    definition: input.definition,
    client: { clientId: input.clientId, clientSecret: null, redirectUri: input.redirectUri },
    state: input.state,
    codeChallenge: input.codeChallenge,
  });
  const url = new URL(authorization.authorizationUrl);
  // Provider-declared extra parameters must never replace application-owned
  // proof material, even if a connector is accidentally misdeclared.
  url.searchParams.set('state', input.state);
  if (input.definition.pkceRequired) {
    url.searchParams.set('code_challenge', input.codeChallenge);
    url.searchParams.set('code_challenge_method', input.codeChallengeMethod);
  }
  return { authorizationUrl: url.toString(), requestedScopes: authorization.scopes };
}

/**
 * The provider package owns registration, while application owns policy. This
 * adapter is the narrow seam between them. A provider is visible to an
 * application service only when the capability detector reports `live`, which
 * includes the explicit definition-of-done allow-list. Credentials alone never
 * make a connector customer-visible.
 *
 * Capability execution remains deliberately unavailable here. It needs the
 * workspace-scoped credential resolver and the worker gateway, which will be
 * added with the first provider dossier. Keeping the method explicit prevents
 * the runtime from accidentally treating a registered adapter as publishable.
 */
export class VerifiedConnectorRegistry implements ApplicationConnectorRegistry {
  readonly #registry: ReturnType<typeof createConnectorRegistry>;
  readonly #capabilities: ReturnType<typeof detectCapabilities>;
  readonly #config: RelayConfig;

  constructor(
    registry: ReturnType<typeof createConnectorRegistry>,
    capabilities: ReturnType<typeof detectCapabilities>,
    config: RelayConfig,
  ) {
    this.#registry = registry;
    this.#capabilities = capabilities;
    this.#config = config;
  }

  has(provider: ProviderId): boolean {
    if (provider === 'fake') return false;
    try {
      return this.#registry.describe(provider, this.#capabilities).configured;
    } catch {
      return false;
    }
  }

  /**
   * Return an adapter only after both production gates have passed:
   * configuration is usable and the connector is explicitly verified. The
   * execution gateway uses this method instead of reaching into the registry,
   * which keeps an accidentally registered beta adapter from receiving a
   * credential or making an external call.
   */
  verifiedConnector(provider: ProviderId, feature: ConnectorFeature): SocialConnector {
    if (!this.has(provider)) {
      throw new RelayError(ERROR_CODES.CAPABILITY_NOT_IMPLEMENTED, {
        messageKey: 'errors.capability_not_implemented',
        details: {
          reason: 'connector_not_verified',
          capability: feature,
          provider,
        },
      });
    }

    const support = this.#registry.featureSupport(provider, feature);
    if (support === 'unsupported') {
      throw new RelayError(ERROR_CODES.CAPABILITY_UNSUPPORTED, {
        messageKey: 'error.capability_unsupported.message',
        details: { capability: feature, provider },
      });
    }
    if (support !== 'supported') {
      throw new RelayError(ERROR_CODES.CAPABILITY_NOT_IMPLEMENTED, {
        messageKey: 'errors.capability_not_implemented',
        details: { capability: feature, provider, support },
      });
    }
    return this.#registry.get(provider);
  }

  /** Read a feature declaration only through the same verified-provider gate. */
  verifiedFeatureSupport(provider: ProviderId, feature: ConnectorFeature): CapabilitySupport {
    if (!this.has(provider)) {
      throw new RelayError(ERROR_CODES.CAPABILITY_NOT_IMPLEMENTED, {
        messageKey: 'errors.capability_not_implemented',
        details: {
          reason: 'connector_not_verified',
          capability: feature,
          provider,
        },
      });
    }
    return this.#registry.featureSupport(provider, feature);
  }

  async beginOAuth(input: {
    readonly provider: ProviderId;
    readonly state: string;
    readonly codeChallenge: string;
    readonly codeChallengeMethod: 'S256';
    readonly redirectUri: string;
  }): Promise<{
    readonly authorizationUrl: string;
    readonly requestedScopes: readonly string[];
  }> {
    if (!this.has(input.provider)) {
      throw new RelayError(ERROR_CODES.CAPABILITY_NOT_IMPLEMENTED, {
        messageKey: 'errors.capability_not_implemented',
        details: {
          reason: 'connector_not_verified',
          capability: 'oauth_start',
          provider: input.provider,
        },
      });
    }
    const clientId = oauthClientId(this.#config, input.provider);
    if (clientId === undefined) {
      throw new RelayError(ERROR_CODES.CAPABILITY_NOT_IMPLEMENTED, {
        messageKey: 'errors.capability_not_implemented',
        details: {
          reason: 'oauth_client_configuration_unavailable',
          capability: 'oauth_start',
          provider: input.provider,
        },
      });
    }
    const definition = authorizationDefinitionSchema.parse(
      this.#registry.get(input.provider).authorization(),
    );
    return buildVerifiedOAuthAuthorizationUrl({
      definition,
      clientId,
      state: input.state,
      codeChallenge: input.codeChallenge,
      codeChallengeMethod: input.codeChallengeMethod,
      redirectUri: input.redirectUri,
    });
  }

  async capabilitiesFor(input: {
    readonly provider: ProviderId;
    readonly connectionId: string;
    readonly accountType: string;
  }): Promise<CapabilitySnapshot> {
    throw new RelayError(ERROR_CODES.CAPABILITY_NOT_IMPLEMENTED, {
      details: {
        reason: 'connector_execution_gateway_not_wired',
        provider: input.provider,
        connectionId: input.connectionId,
        accountType: input.accountType,
      },
    });
  }
}

function connectorLogger(logger: Logger): ConnectorLogger {
  return {
    debug(fields, message): void {
      logger.debug(fields, message);
    },
    info(fields, message): void {
      logger.info(fields, message);
    },
    warn(fields, message): void {
      logger.warn(fields, message);
    },
    error(fields, message): void {
      logger.error(fields, message);
    },
  };
}

/**
 * Compose every adapter for capability introspection without giving any
 * adapter a usable credential vault. The registry marks each adapter with its
 * exact configuration/verification reason, while calls that would cause an
 * external side effect still fail closed in the application gateway.
 */
export function createVerifiedConnectorRegistry(input: {
  readonly config: RelayConfig;
  readonly logger: Logger;
  readonly clock: Clock;
}): VerifiedConnectorRegistry {
  const capabilities = detectCapabilities(input.config);
  const registry = createConnectorRegistry([], { clock: input.clock });
  const http = new ProviderHttpClient({
    provider: 'fake',
    clock: input.clock,
    logger: connectorLogger(input.logger),
  });
  const vault = connectorVaultFromHandles(new Map());
  registerBuiltInProviders(
    registry,
    {
      http: http.asHttpClient(),
      vault,
      clock: input.clock,
      logger: connectorLogger(input.logger),
      config: input.config,
      redirectBaseUrl: input.config.core.apiUrl ?? 'http://127.0.0.1',
    },
    { verifiedProviders: builtInVerifiedProviders(input.config) },
  );

  // Keep this assertion close to composition. It makes an accidental provider
  // omission a boot-time failure instead of a silently incomplete capability
  // matrix when a new built-in adapter is added.
  if (registry.providers().length !== BUILT_IN_PROVIDERS.length) {
    throw new RelayError(ERROR_CODES.INTERNAL, {
      details: {
        reason: 'built_in_connector_registration_incomplete',
        expected: BUILT_IN_PROVIDERS.length,
        actual: registry.providers().length,
      },
    });
  }
  return new VerifiedConnectorRegistry(registry, capabilities, input.config);
}
