import {
  capabilitySnapshotSchema,
  contentVersionSchema,
  growthPlanSchema,
  metricObservationSchema,
  operationRefSchema,
  paginatedSchema,
  providerIdSchema,
  publicationReceiptSchema,
  publishJobSchema,
  validationResultSchema,
  webhookDeliveryLogSchema,
  webhookEndpointSchema,
} from '@relay/contracts';
import { z } from 'zod';

import { cursorQuerySchema } from '../common/pagination';
import {
  apiKeyIdSchema,
  approvalIdSchema,
  brandIdSchema,
  connectionIdSchema,
  contentItemIdSchema,
  feedIdSchema,
  growthPlanIdSchema,
  growthProfileIdSchema,
  mediaIdSchema,
  membershipIdSchema,
  oauthClientIdSchema,
  oauthGrantIdSchema,
  postVariantIdSchema,
  publishJobIdSchema,
  receiptIdSchema,
  ruleIdSchema,
  shortLinkIdSchema,
  webhookDeliveryIdSchema,
  webhookEndpointIdSchema,
  workspaceIdSchema,
} from '../common/schemas';
import { createApiKeySchema, listApiKeysQuerySchema } from '../modules/api-keys/api-keys.schemas';
import {
  decideApprovalSchema,
  listPendingQuerySchema,
  requestApprovalSchema,
} from '../modules/approvals/approvals.schemas';
import {
  actionCenterQuerySchema,
  actionItemSchema,
  snoozeActionSchema,
} from '../modules/action-center/action-center.schemas';
import {
  accountMetricsQuerySchema,
  compareRequestSchema,
  createExperimentSchema,
  listExperimentsQuerySchema,
} from '../modules/analytics/analytics.schemas';
import {
  createRuleSchema,
  listRulesQuerySchema,
  listRunsQuerySchema,
  testRunSchema,
  updateRuleSchema,
} from '../modules/automation-rules/automation-rules.schemas';
import {
  magicLinkSchema,
  passwordResetSchema,
  setAliasSchema,
  signInSchema,
  signOutSchema,
  signUpSchema,
  verifyOtpSchema,
  verifyTotpSchema,
} from '../modules/auth/auth.schemas';
import {
  createCheckoutSchema,
  createPortalLinkSchema,
  usageQuerySchema,
} from '../modules/billing/billing.schemas';
import {
  createBrandSchema,
  listBrandsQuerySchema,
  updateBrandSchema,
} from '../modules/brands/brands.schemas';
import {
  beginOAuthSchema,
  listConnectionsQuerySchema,
  listDestinationsQuerySchema,
  searchMentionsQuerySchema,
} from '../modules/connections/connections.schemas';
import {
  applySetSchema,
  applySignatureSchema,
  createDraftSchema,
  listContentQuerySchema,
  overrideVariantSchema,
  previewQuerySchema,
  setTargetsSchema,
  updateMasterSchema,
} from '../modules/content/content.schemas';
import {
  createOAuthAppSchema,
  listAppsQuerySchema,
  listGrantsQuerySchema,
  updateOAuthAppSchema,
} from '../modules/developer-apps/developer-apps.schemas';
import {
  businessProfileInputSchema,
  confirmBusinessProfileSchema,
  exportPlanQuerySchema,
  generatePlanSchema,
  growthPlanSummarySchema,
  listOpportunitiesQuerySchema,
  listToolsQuerySchema,
  planItemSchema,
} from '../modules/growth/growth.schemas';
import {
  createUploadUrlSchema,
  declareRightsSchema,
  editMediaSchema,
  importFromUrlSchema,
  listMediaQuerySchema,
  setAltTextSchema,
} from '../modules/media/media.schemas';
import { publishNowSchema, retryTargetSchema } from '../modules/publishing/publishing.schemas';
import {
  createFeedSchema,
  listFeedsQuerySchema,
  updateFeedSchema,
  validateFeedSchema,
} from '../modules/rss/rss.schemas';
import {
  calendarQuerySchema,
  cancelRequestSchema,
  nextSlotQuerySchema,
  rescheduleRequestSchema,
  scheduleRequestSchema,
} from '../modules/scheduling/scheduling.schemas';
import {
  createShortLinkSchema,
  listShortLinksQuerySchema,
  shortLinkStatsQuerySchema,
} from '../modules/short-links/short-links.schemas';
import { listAuditQuerySchema } from '../modules/audit/audit.schemas';
import {
  createWebhookEndpointSchema,
  inboundIntegrationSchema,
  updateWebhookEndpointSchema,
} from '../modules/webhooks/webhooks.schemas';
import {
  acceptInvitationSchema,
  createWorkspaceSchema,
  inviteMemberSchema,
  listWorkspacesQuerySchema,
  updateRoleSchema,
  updateWorkspaceSchema,
} from '../modules/workspaces/workspaces.schemas';
import {
  authorizeQuerySchema,
  consentDecisionSchema,
  introspectionRequestSchema,
  revocationRequestSchema,
  tokenRequestSchema,
} from '../oauth-provider/oauth.schemas';
import type { OperationSpec } from './types';

/**
 * The route catalog.
 *
 * Every entry references the exact schema object its controller parses with,
 * imported from the module that owns it. Nothing here is restated, which is
 * what makes the published document incapable of describing a shape the server
 * does not accept.
 *
 * A view model that `@relay/contracts` does not publish a schema for is
 * documented as a generic JSON object rather than as an invented shape. Naming
 * fields we have not committed to would be worse than admitting the gap: a
 * client would code against them.
 */

/** An application view model the API forwards without reshaping. */
const view = z.record(z.string(), z.unknown());
const viewList = z.object({ data: z.array(view) }).strict();
const pagedView = paginatedSchema(view);

const p = (name: string, schema: z.ZodType<string>) => [{ name, schema }] as const;

export const OPERATIONS: readonly OperationSpec[] = [
  /* ---------------------------------------------------------------- health */
  {
    method: 'get',
    path: '/healthz',
    operationId: 'health.live',
    summary: 'Liveness. Answers as soon as the process can serve a request.',
    tag: 'health',
    public: true,
    response: z.object({ status: z.literal('ok') }).strict(),
  },
  {
    method: 'get',
    path: '/v1/health',
    operationId: 'health.ready',
    summary: 'Readiness, with the state of every declared dependency.',
    tag: 'health',
    public: true,
  },
  {
    method: 'get',
    path: '/v1/capabilities',
    operationId: 'health.capabilities',
    summary: 'Which subsystems and connectors this deployment can actually use.',
    tag: 'health',
    public: true,
  },

  /* ------------------------------------------------------------------ auth */
  {
    method: 'post',
    path: '/v1/auth/signup',
    operationId: 'auth.signUp',
    summary: 'Create an identity. Always 202, whether or not the address already exists.',
    tag: 'auth',
    public: true,
    body: signUpSchema,
    successStatus: 202,
  },
  {
    method: 'post',
    path: '/v1/auth/signin',
    operationId: 'auth.signIn',
    summary: 'Sign in with an email address or a username alias, plus a password.',
    tag: 'auth',
    public: true,
    body: signInSchema,
  },
  {
    method: 'post',
    path: '/v1/auth/magic-link',
    operationId: 'auth.magicLink',
    summary: 'Send a one-time code. Always 202.',
    tag: 'auth',
    public: true,
    body: magicLinkSchema,
    successStatus: 202,
  },
  {
    method: 'post',
    path: '/v1/auth/magic-link/verify',
    operationId: 'auth.verifyMagicLink',
    summary: 'Exchange a one-time code for a session.',
    tag: 'auth',
    public: true,
    body: verifyOtpSchema,
  },
  {
    method: 'post',
    path: '/v1/auth/password-reset',
    operationId: 'auth.passwordReset',
    summary: 'Request a password reset. Always 202.',
    tag: 'auth',
    public: true,
    body: passwordResetSchema,
    successStatus: 202,
  },
  {
    method: 'post',
    path: '/v1/auth/session/refresh',
    operationId: 'auth.refresh',
    summary: 'Rotate the session. One-time use; reuse revokes the whole family.',
    tag: 'auth',
    public: true,
  },
  {
    method: 'post',
    path: '/v1/auth/signout',
    operationId: 'auth.signOut',
    summary: 'End this session, or every session this identity holds.',
    tag: 'auth',
    workspaceOptional: true,
    body: signOutSchema,
  },
  {
    method: 'get',
    path: '/v1/auth/me',
    operationId: 'auth.me',
    summary: 'The caller, and the workspaces this credential may address.',
    tag: 'auth',
    workspaceOptional: true,
  },
  {
    method: 'get',
    path: '/v1/auth/session',
    operationId: 'auth.session',
    summary: 'The sanitized browser bootstrap view for the selected workspace.',
    tag: 'auth',
    workspaceOptional: true,
  },
  {
    method: 'post',
    path: '/v1/auth/alias',
    operationId: 'auth.setAlias',
    summary: 'Claim or change the username alias.',
    tag: 'auth',
    workspaceOptional: true,
    requiresStepUp: true,
    body: setAliasSchema,
  },
  {
    method: 'post',
    path: '/v1/auth/mfa/totp',
    operationId: 'auth.enrollTotp',
    summary: 'Begin TOTP enrolment.',
    tag: 'auth',
    workspaceOptional: true,
    requiresStepUp: true,
    successStatus: 201,
  },
  {
    method: 'post',
    path: '/v1/auth/mfa/totp/verify',
    operationId: 'auth.verifyTotp',
    summary: 'Confirm enrolment, or satisfy a step-up, with a six digit code.',
    tag: 'auth',
    workspaceOptional: true,
    body: verifyTotpSchema,
  },

  /* ------------------------------------------------------------ workspaces */
  {
    method: 'get',
    path: '/v1/workspaces',
    operationId: 'workspaces.listMine',
    summary: 'The workspaces this identity belongs to.',
    tag: 'workspaces',
    workspaceOptional: true,
    query: listWorkspacesQuerySchema,
    response: viewList,
  },
  {
    method: 'post',
    path: '/v1/workspaces',
    operationId: 'workspaces.create',
    summary: 'Create a workspace.',
    tag: 'workspaces',
    workspaceOptional: true,
    requiresIdempotencyKey: true,
    body: createWorkspaceSchema,
    successStatus: 201,
    response: view,
  },
  {
    method: 'get',
    path: '/v1/workspaces/{id}',
    operationId: 'workspaces.get',
    summary: 'One workspace.',
    tag: 'workspaces',
    scopes: ['accounts:read'],
    pathParams: p('id', workspaceIdSchema),
    response: view,
  },
  {
    method: 'patch',
    path: '/v1/workspaces/{id}',
    operationId: 'workspaces.update',
    summary: 'Update a workspace.',
    tag: 'workspaces',
    scopes: ['accounts:write'],
    pathParams: p('id', workspaceIdSchema),
    body: updateWorkspaceSchema,
    response: view,
  },
  {
    method: 'get',
    path: '/v1/workspaces/current/members',
    operationId: 'workspaces.listMembers',
    summary: 'Members of the pinned workspace.',
    tag: 'workspaces',
    scopes: ['accounts:read'],
    query: cursorQuerySchema,
    response: pagedView,
  },
  {
    method: 'patch',
    path: '/v1/workspaces/current/members/{id}',
    operationId: 'workspaces.updateRole',
    summary: 'Change a member role. Narrows or widens every credential they created.',
    tag: 'workspaces',
    scopes: ['accounts:write'],
    requiresStepUp: true,
    pathParams: p('id', membershipIdSchema),
    body: updateRoleSchema,
    response: view,
  },
  {
    method: 'delete',
    path: '/v1/workspaces/current/members/{id}',
    operationId: 'workspaces.removeMember',
    summary: 'Remove a member.',
    tag: 'workspaces',
    scopes: ['accounts:write'],
    requiresStepUp: true,
    pathParams: p('id', membershipIdSchema),
    successStatus: 204,
  },
  {
    method: 'get',
    path: '/v1/workspaces/current/invitations',
    operationId: 'workspaces.listInvitations',
    summary: 'Outstanding invitations.',
    tag: 'workspaces',
    scopes: ['accounts:read'],
    query: cursorQuerySchema,
    response: pagedView,
  },
  {
    method: 'post',
    path: '/v1/workspaces/current/invitations',
    operationId: 'workspaces.invite',
    summary: 'Invite someone. Bound to one address, single use, seven day expiry.',
    tag: 'workspaces',
    scopes: ['accounts:write'],
    requiresIdempotencyKey: true,
    body: inviteMemberSchema,
    successStatus: 201,
    response: view,
  },
  {
    method: 'post',
    path: '/v1/workspaces/invitations/accept',
    operationId: 'workspaces.acceptInvitation',
    summary: 'Accept an invitation.',
    tag: 'workspaces',
    workspaceOptional: true,
    requiresIdempotencyKey: true,
    body: acceptInvitationSchema,
    response: view,
  },

  /* ---------------------------------------------------------------- brands */
  {
    method: 'get',
    path: '/v1/brands',
    operationId: 'brands.list',
    summary: 'Brands in the pinned workspace.',
    tag: 'brands',
    scopes: ['accounts:read'],
    query: listBrandsQuerySchema,
    response: pagedView,
  },
  {
    method: 'post',
    path: '/v1/brands',
    operationId: 'brands.create',
    summary: 'Create a brand.',
    tag: 'brands',
    scopes: ['accounts:write'],
    requiresIdempotencyKey: true,
    body: createBrandSchema,
    successStatus: 201,
    response: view,
  },
  {
    method: 'get',
    path: '/v1/brands/{id}',
    operationId: 'brands.get',
    summary: 'One brand.',
    tag: 'brands',
    scopes: ['accounts:read'],
    pathParams: p('id', brandIdSchema),
    response: view,
  },
  {
    method: 'patch',
    path: '/v1/brands/{id}',
    operationId: 'brands.update',
    summary: 'Update a brand.',
    tag: 'brands',
    scopes: ['accounts:write'],
    pathParams: p('id', brandIdSchema),
    body: updateBrandSchema,
    response: view,
  },
  {
    method: 'delete',
    path: '/v1/brands/{id}',
    operationId: 'brands.delete',
    summary: 'Delete a brand.',
    tag: 'brands',
    scopes: ['accounts:write'],
    pathParams: p('id', brandIdSchema),
    successStatus: 204,
  },

  /* ----------------------------------------------------------- connections */
  {
    method: 'get',
    path: '/v1/connections/providers',
    operationId: 'connections.listAvailableProviders',
    summary: 'Provider connectors this deployment has verified and enabled.',
    tag: 'connections',
    scopes: ['accounts:read'],
    response: z.array(providerIdSchema),
  },
  {
    method: 'get',
    path: '/v1/connections',
    operationId: 'connections.list',
    summary: 'Connected accounts, with health.',
    tag: 'connections',
    scopes: ['accounts:read'],
    query: listConnectionsQuerySchema,
    response: pagedView,
  },
  {
    method: 'get',
    path: '/v1/connections/{id}',
    operationId: 'connections.get',
    summary: 'One connection.',
    tag: 'connections',
    scopes: ['accounts:read'],
    pathParams: p('id', connectionIdSchema),
    response: view,
  },
  {
    method: 'get',
    path: '/v1/connections/{id}/capabilities',
    operationId: 'connections.capabilities',
    summary: 'What this account can do now. Keeps `unsupported` and `not_implemented` apart.',
    tag: 'connections',
    scopes: ['accounts:read'],
    pathParams: p('id', connectionIdSchema),
    response: capabilitySnapshotSchema,
  },
  {
    method: 'post',
    path: '/v1/connections/oauth/begin',
    operationId: 'connections.beginOAuth',
    summary: 'Start a provider handshake.',
    tag: 'connections',
    scopes: ['connections:admin'],
    requiresStepUp: true,
    requiresIdempotencyKey: true,
    body: beginOAuthSchema,
    response: z.object({ authorizationUrl: z.string(), transactionId: z.string() }).strict(),
  },
  {
    method: 'post',
    path: '/v1/connections/{id}/reconnect',
    operationId: 'connections.reconnect',
    summary: 'Re-authorize an existing connection.',
    tag: 'connections',
    scopes: ['connections:admin'],
    requiresStepUp: true,
    requiresIdempotencyKey: true,
    pathParams: p('id', connectionIdSchema),
    response: view,
  },
  {
    method: 'post',
    path: '/v1/connections/{id}/pause',
    operationId: 'connections.pause',
    summary: 'Pause publishing to this account.',
    tag: 'connections',
    scopes: ['connections:admin'],
    requiresIdempotencyKey: true,
    pathParams: p('id', connectionIdSchema),
    response: view,
  },
  {
    method: 'post',
    path: '/v1/connections/{id}/resume',
    operationId: 'connections.resume',
    summary: 'Resume publishing to this account.',
    tag: 'connections',
    scopes: ['connections:admin'],
    requiresIdempotencyKey: true,
    pathParams: p('id', connectionIdSchema),
    response: view,
  },
  {
    method: 'post',
    path: '/v1/connections/{id}/disconnect',
    operationId: 'connections.disconnect',
    summary: 'Disconnect, and revoke at the provider where one exists.',
    tag: 'connections',
    scopes: ['connections:admin'],
    requiresStepUp: true,
    requiresIdempotencyKey: true,
    pathParams: p('id', connectionIdSchema),
    response: view,
  },
  {
    method: 'get',
    path: '/v1/connections/{id}/destinations',
    operationId: 'connections.listDestinations',
    summary: 'Native destinations inside an account.',
    tag: 'connections',
    scopes: ['accounts:read'],
    pathParams: p('id', connectionIdSchema),
    query: listDestinationsQuerySchema,
    response: z.array(view),
  },
  {
    method: 'get',
    path: '/v1/connections/{id}/mentions',
    operationId: 'connections.searchMentions',
    summary: 'Resolve a handle to a real account on the platform.',
    tag: 'connections',
    scopes: ['accounts:read'],
    pathParams: p('id', connectionIdSchema),
    query: searchMentionsQuerySchema,
    response: z.array(view),
  },

  /* --------------------------------------------------------------- content */
  {
    method: 'get',
    path: '/v1/content',
    operationId: 'content.list',
    summary: 'Content items.',
    tag: 'content',
    scopes: ['drafts:read'],
    query: listContentQuerySchema,
    response: pagedView,
  },
  {
    method: 'post',
    path: '/v1/content',
    operationId: 'content.createDraft',
    summary: 'Create a draft with a master and its targets.',
    tag: 'content',
    scopes: ['drafts:write'],
    requiresIdempotencyKey: true,
    body: createDraftSchema,
    successStatus: 201,
    response: view,
  },
  {
    method: 'get',
    path: '/v1/content/{id}',
    operationId: 'content.get',
    summary: 'One content item.',
    tag: 'content',
    scopes: ['drafts:read'],
    pathParams: p('id', contentItemIdSchema),
    response: view,
  },
  {
    method: 'patch',
    path: '/v1/content/{id}',
    operationId: 'content.updateMaster',
    summary: 'Edit the master. Reaches every target that has not overridden the field.',
    tag: 'content',
    scopes: ['drafts:write'],
    pathParams: p('id', contentItemIdSchema),
    body: updateMasterSchema,
    response: view,
  },
  {
    method: 'delete',
    path: '/v1/content/{id}',
    operationId: 'content.delete',
    summary: 'Delete a draft.',
    tag: 'content',
    scopes: ['drafts:write'],
    pathParams: p('id', contentItemIdSchema),
    successStatus: 204,
  },
  {
    method: 'put',
    path: '/v1/content/{id}/targets',
    operationId: 'content.setTargets',
    summary: 'Replace the target set.',
    tag: 'content',
    scopes: ['drafts:write'],
    pathParams: p('id', contentItemIdSchema),
    body: setTargetsSchema,
    response: view,
  },
  {
    method: 'patch',
    path: '/v1/content/{id}/variants/{targetId}',
    operationId: 'content.overrideVariant',
    summary: 'Override fields for one target. Omitted fields keep inheriting.',
    tag: 'content',
    scopes: ['drafts:write'],
    pathParams: [
      { name: 'id', schema: contentItemIdSchema },
      { name: 'targetId', schema: postVariantIdSchema },
    ],
    body: overrideVariantSchema,
    response: view,
  },
  {
    method: 'delete',
    path: '/v1/content/{id}/variants/{targetId}/overrides',
    operationId: 'content.resetVariant',
    summary: 'Drop every override so the target follows the master again.',
    tag: 'content',
    scopes: ['drafts:write'],
    pathParams: [
      { name: 'id', schema: contentItemIdSchema },
      { name: 'targetId', schema: postVariantIdSchema },
    ],
    response: view,
  },
  {
    method: 'get',
    path: '/v1/content/{id}/preview',
    operationId: 'content.preview',
    summary: 'Exactly what one target will look like on that platform.',
    tag: 'content',
    scopes: ['drafts:read'],
    pathParams: p('id', contentItemIdSchema),
    query: previewQuerySchema,
    response: view,
  },
  {
    method: 'post',
    path: '/v1/content/{id}/validate',
    operationId: 'content.validate',
    summary: 'Deterministic validation and a provider cost estimate.',
    tag: 'content',
    scopes: ['drafts:read'],
    pathParams: p('id', contentItemIdSchema),
    response: validationResultSchema,
  },
  {
    method: 'post',
    path: '/v1/content/{id}/versions',
    operationId: 'content.freezeVersion',
    summary: 'Freeze an immutable, checksummed version. Publishing binds to this.',
    tag: 'content',
    scopes: ['drafts:write'],
    requiresIdempotencyKey: true,
    pathParams: p('id', contentItemIdSchema),
    successStatus: 201,
    response: contentVersionSchema,
  },
  {
    method: 'post',
    path: '/v1/content/{id}/apply-set',
    operationId: 'content.applySet',
    summary: 'Apply a saved group of accounts and their per-target defaults.',
    tag: 'content',
    scopes: ['drafts:write'],
    pathParams: p('id', contentItemIdSchema),
    body: applySetSchema,
    response: view,
  },
  {
    method: 'post',
    path: '/v1/content/{id}/apply-signature',
    operationId: 'content.applySignature',
    summary: 'Apply a signature to the master, or to one target.',
    tag: 'content',
    scopes: ['drafts:write'],
    pathParams: p('id', contentItemIdSchema),
    body: applySignatureSchema,
    response: view,
  },

  /* ------------------------------------------------------------- approvals */
  {
    method: 'get',
    path: '/v1/approvals/pending',
    operationId: 'approvals.listPending',
    summary: 'Reviews waiting on this actor.',
    tag: 'approvals',
    scopes: ['drafts:read'],
    query: listPendingQuerySchema,
    response: pagedView,
  },
  {
    method: 'post',
    path: '/v1/approvals',
    operationId: 'approvals.request',
    summary: 'Route a draft into the approval policy.',
    tag: 'approvals',
    scopes: ['drafts:write'],
    requiresIdempotencyKey: true,
    body: requestApprovalSchema,
    successStatus: 201,
    response: view,
  },
  {
    method: 'post',
    path: '/v1/approvals/{id}/decision',
    operationId: 'approvals.decide',
    summary: 'Approve or reject. Records the content version hash it applied to.',
    tag: 'approvals',
    scopes: ['posts:schedule'],
    requiresIdempotencyKey: true,
    pathParams: p('id', approvalIdSchema),
    body: decideApprovalSchema,
    response: view,
  },

  /* --------------------------------------------------------- action center */
  {
    method: 'get',
    path: '/v1/action-center',
    operationId: 'actionCenter.list',
    summary: 'Evidence-backed situations that need a person in the current workspace.',
    tag: 'action-center',
    scopes: ['drafts:read'],
    query: actionCenterQuerySchema,
    response: paginatedSchema(actionItemSchema),
  },
  {
    method: 'post',
    path: '/v1/action-center/{id}/snooze',
    operationId: 'actionCenter.snooze',
    summary: 'Hide one action item until a future instant.',
    tag: 'action-center',
    scopes: ['drafts:read'],
    requiresIdempotencyKey: true,
    pathParams: p('id', z.string().min(1).max(255)),
    body: snoozeActionSchema,
    response: actionItemSchema,
  },
  {
    method: 'delete',
    path: '/v1/action-center/{id}/snooze',
    operationId: 'actionCenter.unsnooze',
    summary: 'Return a snoozed action item to the queue.',
    tag: 'action-center',
    scopes: ['drafts:read'],
    pathParams: p('id', z.string().min(1).max(255)),
    successStatus: 204,
  },

  /* ------------------------------------------------------------ scheduling */
  {
    method: 'post',
    path: '/v1/schedules',
    operationId: 'scheduling.schedule',
    summary: 'Schedule a content item.',
    tag: 'scheduling',
    scopes: ['posts:schedule'],
    requiresIdempotencyKey: true,
    body: scheduleRequestSchema,
    successStatus: 202,
    response: publishJobSchema,
  },
  {
    method: 'post',
    path: '/v1/schedules/{id}/reschedule',
    operationId: 'scheduling.reschedule',
    summary: 'Move a scheduled job. Ambiguous local times require confirmation.',
    tag: 'scheduling',
    scopes: ['posts:schedule'],
    requiresIdempotencyKey: true,
    pathParams: p('id', publishJobIdSchema),
    body: rescheduleRequestSchema,
    response: publishJobSchema,
  },
  {
    method: 'post',
    path: '/v1/schedules/{id}/cancel',
    operationId: 'scheduling.cancel',
    summary: 'Cancel a scheduled job.',
    tag: 'scheduling',
    scopes: ['posts:cancel'],
    requiresIdempotencyKey: true,
    pathParams: p('id', publishJobIdSchema),
    body: cancelRequestSchema,
    response: publishJobSchema,
  },
  {
    method: 'get',
    path: '/v1/calendar',
    operationId: 'scheduling.calendar',
    summary: 'The calendar window. Cursor paginated and zone-qualified.',
    tag: 'scheduling',
    scopes: ['drafts:read'],
    query: calendarQuerySchema,
    response: pagedView,
  },
  {
    method: 'get',
    path: '/v1/calendar/next-slot',
    operationId: 'scheduling.nextSlot',
    summary: 'The next slot that respects cadence and quiet hours.',
    tag: 'scheduling',
    scopes: ['drafts:read'],
    query: nextSlotQuerySchema,
  },

  /* ------------------------------------------------------------ publishing */
  {
    method: 'post',
    path: '/v1/publications',
    operationId: 'publishing.publishNow',
    summary: 'Publish immediately. Requires an explicit human confirmation payload.',
    tag: 'publishing',
    scopes: ['posts:publish'],
    requiresIdempotencyKey: true,
    body: publishNowSchema,
    successStatus: 202,
    response: publishJobSchema,
  },
  {
    method: 'get',
    path: '/v1/jobs/{id}',
    operationId: 'publishing.getJob',
    summary: 'Job status, with every attempt and its classified error.',
    tag: 'publishing',
    scopes: ['drafts:read'],
    pathParams: p('id', publishJobIdSchema),
    response: publishJobSchema,
  },
  {
    method: 'post',
    path: '/v1/jobs/{id}/retry',
    operationId: 'publishing.retryTarget',
    summary: 'Retry one failed target. Successful targets are left alone.',
    tag: 'publishing',
    scopes: ['posts:publish'],
    requiresIdempotencyKey: true,
    pathParams: p('id', publishJobIdSchema),
    body: retryTargetSchema,
    successStatus: 202,
    response: publishJobSchema,
  },
  {
    method: 'get',
    path: '/v1/jobs/{id}/receipts',
    operationId: 'publishing.listReceipts',
    summary: 'Every receipt this job produced.',
    tag: 'publishing',
    scopes: ['analytics:read'],
    pathParams: p('id', publishJobIdSchema),
    response: z.object({ data: z.array(publicationReceiptSchema) }).strict(),
  },
  {
    method: 'get',
    path: '/v1/receipts',
    operationId: 'publishing.listRecentReceipts',
    summary: 'Recent immutable publication receipts for the current workspace.',
    tag: 'publishing',
    scopes: ['analytics:read'],
    query: cursorQuerySchema,
    response: pagedView,
  },
  {
    method: 'get',
    path: '/v1/receipts/{id}',
    operationId: 'publishing.getReceipt',
    summary: 'One publication receipt.',
    tag: 'publishing',
    scopes: ['analytics:read'],
    pathParams: p('id', receiptIdSchema),
    response: publicationReceiptSchema,
  },

  /* ----------------------------------------------------------------- media */
  {
    method: 'get',
    path: '/v1/media',
    operationId: 'media.list',
    summary: 'The media library.',
    tag: 'media',
    scopes: ['media:read'],
    query: listMediaQuerySchema,
    response: pagedView,
  },
  {
    method: 'get',
    path: '/v1/media/{id}',
    operationId: 'media.get',
    summary: 'One asset.',
    tag: 'media',
    scopes: ['media:read'],
    pathParams: p('id', mediaIdSchema),
    response: view,
  },
  {
    method: 'post',
    path: '/v1/media/uploads',
    operationId: 'media.createUploadUrl',
    summary: 'A short-lived signed upload URL for one object key.',
    tag: 'media',
    scopes: ['media:write'],
    requiresIdempotencyKey: true,
    body: createUploadUrlSchema,
    successStatus: 201,
  },
  {
    method: 'post',
    path: '/v1/media/{id}/finalize',
    operationId: 'media.finalize',
    summary: 'Hand the asset to the scan and processing pipeline.',
    tag: 'media',
    scopes: ['media:write'],
    requiresIdempotencyKey: true,
    pathParams: p('id', mediaIdSchema),
    successStatus: 202,
    response: view,
  },
  {
    method: 'post',
    path: '/v1/media/imports',
    operationId: 'media.importFromUrl',
    summary: 'Import from a URL. Asynchronous and SSRF-safe.',
    tag: 'media',
    scopes: ['media:write'],
    requiresIdempotencyKey: true,
    body: importFromUrlSchema,
    successStatus: 202,
    response: operationRefSchema,
  },
  {
    method: 'post',
    path: '/v1/media/{id}/edits',
    operationId: 'media.edit',
    summary: 'Crop, resize, rotate, compress. Nothing generative.',
    tag: 'media',
    scopes: ['media:write'],
    requiresIdempotencyKey: true,
    pathParams: p('id', mediaIdSchema),
    body: editMediaSchema,
    response: view,
  },
  {
    method: 'put',
    path: '/v1/media/{id}/alt-text',
    operationId: 'media.setAltText',
    summary: 'Set alt text, or waive it explicitly.',
    tag: 'media',
    scopes: ['media:write'],
    pathParams: p('id', mediaIdSchema),
    body: setAltTextSchema,
    response: view,
  },
  {
    method: 'put',
    path: '/v1/media/{id}/rights',
    operationId: 'media.declareRights',
    summary: 'Record file ownership, permission and consent.',
    tag: 'media',
    scopes: ['media:write'],
    pathParams: p('id', mediaIdSchema),
    body: declareRightsSchema,
    response: view,
  },
  {
    method: 'delete',
    path: '/v1/media/{id}',
    operationId: 'media.delete',
    summary: 'Delete an asset.',
    tag: 'media',
    scopes: ['media:write'],
    pathParams: p('id', mediaIdSchema),
    successStatus: 204,
  },

  /* ------------------------------------------------------------- analytics */
  {
    method: 'get',
    path: '/v1/analytics/posts/{id}',
    operationId: 'analytics.postMetrics',
    summary: 'Metrics for one external publication, keyed by its receipt.',
    tag: 'analytics',
    scopes: ['analytics:read'],
    pathParams: p('id', receiptIdSchema),
    response: z.object({ data: z.array(metricObservationSchema) }).strict(),
  },
  {
    method: 'get',
    path: '/v1/analytics/accounts',
    operationId: 'analytics.accountMetrics',
    summary: 'Account metrics over an explicit, zone-qualified window.',
    tag: 'analytics',
    scopes: ['analytics:read'],
    query: accountMetricsQuerySchema,
    response: z.object({ data: z.array(metricObservationSchema) }).strict(),
  },
  {
    method: 'post',
    path: '/v1/analytics/comparisons',
    operationId: 'analytics.compare',
    summary: 'Compare receipts, or a period against a baseline.',
    tag: 'analytics',
    scopes: ['analytics:read'],
    body: compareRequestSchema,
    response: view,
  },
  {
    method: 'get',
    path: '/v1/analytics/experiments',
    operationId: 'analytics.listExperiments',
    summary: 'Experiments.',
    tag: 'analytics',
    scopes: ['analytics:read'],
    query: listExperimentsQuerySchema,
    response: pagedView,
  },
  {
    method: 'post',
    path: '/v1/analytics/experiments',
    operationId: 'analytics.createExperiment',
    summary: 'Create an experiment, naming its primary metric up front.',
    tag: 'analytics',
    scopes: ['analytics:read', 'drafts:write'],
    requiresIdempotencyKey: true,
    body: createExperimentSchema,
    successStatus: 201,
    response: view,
  },

  /* ----------------------------------------------------------- short links */
  {
    method: 'get',
    path: '/v1/short-links',
    operationId: 'shortLinks.list',
    summary: 'Short links.',
    tag: 'short-links',
    scopes: ['analytics:read'],
    query: listShortLinksQuerySchema,
    response: pagedView,
  },
  {
    method: 'post',
    path: '/v1/short-links',
    operationId: 'shortLinks.create',
    summary: 'Shorten a destination. The exact destination stays inspectable.',
    tag: 'short-links',
    scopes: ['drafts:write'],
    requiresIdempotencyKey: true,
    body: createShortLinkSchema,
    successStatus: 201,
    response: view,
  },
  {
    method: 'get',
    path: '/v1/short-links/{id}/stats',
    operationId: 'shortLinks.stats',
    summary: 'Total requests and deduplicated human clicks, reported separately.',
    tag: 'short-links',
    scopes: ['analytics:read'],
    pathParams: p('id', shortLinkIdSchema),
    query: shortLinkStatsQuerySchema,
    response: view,
  },

  /* ------------------------------------------------------ automation rules */
  {
    method: 'get',
    path: '/v1/automation-rules',
    operationId: 'automationRules.list',
    summary: 'Automation Rules.',
    tag: 'automation-rules',
    scopes: ['rules:read'],
    query: listRulesQuerySchema,
    response: pagedView,
  },
  {
    method: 'post',
    path: '/v1/automation-rules',
    operationId: 'automationRules.create',
    summary: 'Create a rule. Always created disabled.',
    tag: 'automation-rules',
    scopes: ['rules:write'],
    requiresIdempotencyKey: true,
    body: createRuleSchema,
    successStatus: 201,
    response: view,
  },
  {
    method: 'get',
    path: '/v1/automation-rules/{id}',
    operationId: 'automationRules.get',
    summary: 'One rule.',
    tag: 'automation-rules',
    scopes: ['rules:read'],
    pathParams: p('id', ruleIdSchema),
    response: view,
  },
  {
    method: 'patch',
    path: '/v1/automation-rules/{id}',
    operationId: 'automationRules.update',
    summary: 'Update a rule.',
    tag: 'automation-rules',
    scopes: ['rules:write'],
    pathParams: p('id', ruleIdSchema),
    body: updateRuleSchema,
    response: view,
  },
  {
    method: 'get',
    path: '/v1/automation-rules/{id}/preview',
    operationId: 'automationRules.preview',
    summary: 'Accounts reached, maximum external actions, approvals, cost estimate.',
    tag: 'automation-rules',
    scopes: ['rules:read'],
    pathParams: p('id', ruleIdSchema),
    response: view,
  },
  {
    method: 'post',
    path: '/v1/automation-rules/{id}/test-runs',
    operationId: 'automationRules.testRun',
    summary: 'Run against a sample event. Produces no external action.',
    tag: 'automation-rules',
    scopes: ['rules:read'],
    pathParams: p('id', ruleIdSchema),
    body: testRunSchema,
    response: view,
  },
  {
    method: 'get',
    path: '/v1/automation-rules/{id}/runs',
    operationId: 'automationRules.listRuns',
    summary: 'Run history.',
    tag: 'automation-rules',
    scopes: ['rules:read'],
    pathParams: p('id', ruleIdSchema),
    query: listRunsQuerySchema,
    response: pagedView,
  },
  {
    method: 'post',
    path: '/v1/automation-rules/{id}/enable',
    operationId: 'automationRules.enable',
    summary: 'Enable a rule.',
    tag: 'automation-rules',
    scopes: ['rules:write'],
    requiresStepUp: true,
    requiresIdempotencyKey: true,
    pathParams: p('id', ruleIdSchema),
    response: view,
  },
  {
    method: 'post',
    path: '/v1/automation-rules/{id}/disable',
    operationId: 'automationRules.disable',
    summary: 'Disable a rule.',
    tag: 'automation-rules',
    scopes: ['rules:write'],
    requiresIdempotencyKey: true,
    pathParams: p('id', ruleIdSchema),
    response: view,
  },
  {
    method: 'delete',
    path: '/v1/automation-rules/{id}',
    operationId: 'automationRules.delete',
    summary: 'Delete a rule.',
    tag: 'automation-rules',
    scopes: ['rules:write'],
    pathParams: p('id', ruleIdSchema),
    successStatus: 204,
  },

  /* ------------------------------------------------------------------- rss */
  {
    method: 'get',
    path: '/v1/rss/feeds',
    operationId: 'rss.list',
    summary: 'Feeds.',
    tag: 'rss',
    scopes: ['rules:read'],
    query: listFeedsQuerySchema,
    response: pagedView,
  },
  {
    method: 'post',
    path: '/v1/rss/feeds/validate',
    operationId: 'rss.validate',
    summary: 'Fetch once and preview. Creates nothing.',
    tag: 'rss',
    scopes: ['rules:read'],
    body: validateFeedSchema,
    response: view,
  },
  {
    method: 'post',
    path: '/v1/rss/feeds',
    operationId: 'rss.create',
    summary: 'Add a feed.',
    tag: 'rss',
    scopes: ['rules:write'],
    requiresIdempotencyKey: true,
    body: createFeedSchema,
    successStatus: 201,
    response: view,
  },
  {
    method: 'patch',
    path: '/v1/rss/feeds/{id}',
    operationId: 'rss.update',
    summary: 'Update a feed.',
    tag: 'rss',
    scopes: ['rules:write'],
    pathParams: p('id', feedIdSchema),
    body: updateFeedSchema,
    response: view,
  },
  {
    method: 'get',
    path: '/v1/rss/feeds/{id}/health',
    operationId: 'rss.health',
    summary: 'Last successful fetch, last error, items produced.',
    tag: 'rss',
    scopes: ['rules:read'],
    pathParams: p('id', feedIdSchema),
    response: view,
  },
  {
    method: 'delete',
    path: '/v1/rss/feeds/{id}',
    operationId: 'rss.delete',
    summary: 'Remove a feed.',
    tag: 'rss',
    scopes: ['rules:write'],
    pathParams: p('id', feedIdSchema),
    successStatus: 204,
  },

  /* ---------------------------------------------------------------- growth */
  {
    method: 'get',
    path: '/v1/growth/profile',
    operationId: 'growth.getProfile',
    summary: 'The latest business profile in the workspace.',
    tag: 'growth',
    scopes: ['growth:read'],
    response: view.nullable(),
  },
  {
    method: 'put',
    path: '/v1/growth/profile',
    operationId: 'growth.upsertProfile',
    summary: 'Create or update the business profile.',
    tag: 'growth',
    scopes: ['growth:write'],
    body: businessProfileInputSchema,
    response: view,
  },
  {
    method: 'post',
    path: '/v1/growth/profile/{id}/confirm',
    operationId: 'growth.confirmProfile',
    summary: 'Confirm the intake. A plan is generated only from a confirmed profile.',
    tag: 'growth',
    scopes: ['growth:write'],
    requiresIdempotencyKey: true,
    pathParams: p('id', growthProfileIdSchema),
    body: confirmBusinessProfileSchema,
    response: view,
  },
  {
    method: 'post',
    path: '/v1/growth/plans',
    operationId: 'growth.generatePlan',
    summary: 'Generate a plan. Returns not implemented until the durable worker is enabled.',
    tag: 'growth',
    scopes: ['growth:write'],
    requiresIdempotencyKey: true,
    body: generatePlanSchema,
    successStatus: 202,
    response: operationRefSchema,
  },
  {
    method: 'get',
    path: '/v1/growth/plans/current/summary',
    operationId: 'growth.getPlanSummary',
    summary: 'The current approved plan summary for Home.',
    tag: 'growth',
    scopes: ['growth:read'],
    response: growthPlanSummarySchema,
  },
  {
    method: 'get',
    path: '/v1/growth/plans/current',
    operationId: 'growth.getCurrentPlan',
    summary: 'The latest current growth plan.',
    tag: 'growth',
    scopes: ['growth:read'],
    response: growthPlanSchema.nullable(),
  },
  {
    method: 'get',
    path: '/v1/growth/plans/{id}',
    operationId: 'growth.getPlan',
    summary: 'A plan, separating facts from assumptions.',
    tag: 'growth',
    scopes: ['growth:read'],
    pathParams: p('id', growthPlanIdSchema),
    response: growthPlanSchema,
  },
  {
    method: 'get',
    path: '/v1/growth/plans/{id}/export',
    operationId: 'growth.exportPlan',
    summary: 'Export the validated plan as Markdown, JSON or YAML.',
    tag: 'growth',
    scopes: ['growth:read'],
    pathParams: p('id', growthPlanIdSchema),
    query: exportPlanQuerySchema,
  },
  {
    method: 'post',
    path: '/v1/growth/plans/{id}/drafts',
    operationId: 'growth.createDraftFromItem',
    summary: 'Turn one selected plan item into a draft.',
    tag: 'growth',
    scopes: ['growth:write', 'drafts:write'],
    requiresIdempotencyKey: true,
    pathParams: p('id', growthPlanIdSchema),
    body: planItemSchema.omit({ planId: true }),
    successStatus: 201,
    response: view,
  },
  {
    method: 'post',
    path: '/v1/growth/plans/{id}/slot-proposals',
    operationId: 'growth.proposeSlot',
    summary: 'Propose a calendar slot for one item. A proposal, not a schedule.',
    tag: 'growth',
    scopes: ['growth:write'],
    requiresIdempotencyKey: true,
    pathParams: p('id', growthPlanIdSchema),
    body: planItemSchema.omit({ planId: true }),
    response: view,
  },
  {
    method: 'get',
    path: '/v1/growth/opportunities',
    operationId: 'growth.listOpportunities',
    summary: 'Catalog-backed opportunities, each with an official URL and a verified date.',
    tag: 'growth',
    scopes: ['growth:read'],
    query: listOpportunitiesQuerySchema,
    response: viewList,
  },
  {
    method: 'get',
    path: '/v1/growth/tools',
    operationId: 'growth.listTools',
    summary: 'The tool radar, from the same verified catalog.',
    tag: 'growth',
    scopes: ['growth:read'],
    query: listToolsQuerySchema,
    response: viewList,
  },

  /* -------------------------------------------------------------- webhooks */
  {
    method: 'get',
    path: '/v1/webhooks/endpoints',
    operationId: 'webhooks.list',
    summary: 'Outbound endpoints.',
    tag: 'webhooks',
    scopes: ['webhooks:manage'],
    query: cursorQuerySchema,
    response: paginatedSchema(webhookEndpointSchema),
  },
  {
    method: 'post',
    path: '/v1/webhooks/endpoints',
    operationId: 'webhooks.create',
    summary: 'Register an endpoint.',
    tag: 'webhooks',
    scopes: ['webhooks:manage'],
    requiresIdempotencyKey: true,
    body: createWebhookEndpointSchema,
    successStatus: 201,
    response: z
      .object({ endpoint: webhookEndpointSchema, signingSecret: z.string().min(20) })
      .strict(),
  },
  {
    method: 'patch',
    path: '/v1/webhooks/endpoints/{id}',
    operationId: 'webhooks.update',
    summary: 'Update an endpoint.',
    tag: 'webhooks',
    scopes: ['webhooks:manage'],
    pathParams: p('id', webhookEndpointIdSchema),
    body: updateWebhookEndpointSchema,
    response: webhookEndpointSchema,
  },
  {
    method: 'delete',
    path: '/v1/webhooks/endpoints/{id}',
    operationId: 'webhooks.delete',
    summary: 'Delete an endpoint.',
    tag: 'webhooks',
    scopes: ['webhooks:manage'],
    pathParams: p('id', webhookEndpointIdSchema),
    successStatus: 204,
  },
  {
    method: 'post',
    path: '/v1/webhooks/endpoints/{id}/test',
    operationId: 'webhooks.test',
    summary: 'Send a test event, marked `isTest` so a receiver cannot mistake it.',
    tag: 'webhooks',
    scopes: ['webhooks:manage'],
    requiresIdempotencyKey: true,
    pathParams: p('id', webhookEndpointIdSchema),
    successStatus: 202,
    response: webhookDeliveryLogSchema,
  },
  {
    method: 'get',
    path: '/v1/webhooks/endpoints/{id}/deliveries',
    operationId: 'webhooks.listDeliveries',
    summary: 'Delivery log, with response status and a redacted body prefix.',
    tag: 'webhooks',
    scopes: ['webhooks:manage'],
    pathParams: p('id', webhookEndpointIdSchema),
    query: cursorQuerySchema,
    response: paginatedSchema(webhookDeliveryLogSchema),
  },
  {
    method: 'post',
    path: '/v1/webhooks/deliveries/{id}/redeliver',
    operationId: 'webhooks.redeliver',
    summary: 'Resend one delivery. The envelope id is stable, so receivers dedupe.',
    tag: 'webhooks',
    scopes: ['webhooks:manage'],
    requiresIdempotencyKey: true,
    pathParams: p('id', webhookDeliveryIdSchema),
    successStatus: 202,
    response: webhookDeliveryLogSchema,
  },
  {
    method: 'post',
    path: '/v1/integrations/inbound',
    operationId: 'integrations.inbound',
    summary:
      'Create a draft or start a named rule from JSON. Cannot publish; enters the normal workflow.',
    tag: 'webhooks',
    scopes: ['rules:write'],
    requiresIdempotencyKey: true,
    body: inboundIntegrationSchema,
    successStatus: 202,
  },
  {
    method: 'post',
    path: '/v1/webhooks/polar',
    operationId: 'billing.polarWebhook',
    summary: 'Polar receiver. Signature is verified over the raw bytes before the body is parsed.',
    tag: 'billing',
    public: true,
  },

  /* --------------------------------------------------------------- billing */
  {
    method: 'get',
    path: '/v1/billing/entitlements',
    operationId: 'billing.entitlements',
    summary: 'Plan, trial state, and what the workspace may currently do.',
    tag: 'billing',
    scopes: ['billing:read'],
    response: view,
  },
  {
    method: 'get',
    path: '/v1/billing/usage',
    operationId: 'billing.usage',
    summary: 'Metered usage: provider pass-through cost and AI text tokens.',
    tag: 'billing',
    scopes: ['billing:read'],
    query: usageQuerySchema,
    response: view,
  },
  {
    method: 'post',
    path: '/v1/billing/checkout',
    operationId: 'billing.checkout',
    summary: 'Start a hosted checkout. The redirect grants no entitlement.',
    tag: 'billing',
    scopes: ['billing:read'],
    requiresStepUp: true,
    requiresIdempotencyKey: true,
    body: createCheckoutSchema,
    successStatus: 201,
    response: view,
  },
  {
    method: 'post',
    path: '/v1/billing/portal',
    operationId: 'billing.portal',
    summary: 'A link to the customer portal.',
    tag: 'billing',
    scopes: ['billing:read'],
    requiresStepUp: true,
    body: createPortalLinkSchema,
    successStatus: 201,
    response: view,
  },

  /* -------------------------------------------------------------- api keys */
  {
    method: 'get',
    path: '/v1/api-keys',
    operationId: 'apiKeys.list',
    summary: 'Workspace API keys.',
    tag: 'api-keys',
    scopes: ['connections:admin'],
    query: listApiKeysQuerySchema,
    response: pagedView,
  },
  {
    method: 'post',
    path: '/v1/api-keys',
    operationId: 'apiKeys.create',
    summary: 'Create a key. The secret is returned exactly once.',
    tag: 'api-keys',
    scopes: ['connections:admin'],
    requiresStepUp: true,
    requiresIdempotencyKey: true,
    body: createApiKeySchema,
    successStatus: 201,
    response: z.object({ key: view, secret: z.string().min(20) }).strict(),
  },
  {
    method: 'delete',
    path: '/v1/api-keys/{id}',
    operationId: 'apiKeys.revoke',
    summary: 'Revoke a key. Effective on the next request.',
    tag: 'api-keys',
    scopes: ['connections:admin'],
    requiresStepUp: true,
    pathParams: p('id', apiKeyIdSchema),
    successStatus: 204,
  },

  /* ------------------------------------------------------- developer apps */
  {
    method: 'get',
    path: '/v1/developer/apps',
    operationId: 'developerApps.list',
    summary: 'Registered OAuth applications.',
    tag: 'developer',
    scopes: ['connections:admin'],
    query: listAppsQuerySchema,
    response: pagedView,
  },
  {
    method: 'post',
    path: '/v1/developer/apps',
    operationId: 'developerApps.create',
    summary: 'Register an app with an exact redirect URI allowlist.',
    tag: 'developer',
    scopes: ['connections:admin'],
    requiresStepUp: true,
    requiresIdempotencyKey: true,
    body: createOAuthAppSchema,
    successStatus: 201,
    response: view,
  },
  {
    method: 'get',
    path: '/v1/developer/apps/{id}',
    operationId: 'developerApps.get',
    summary: 'One application.',
    tag: 'developer',
    scopes: ['connections:admin'],
    pathParams: p('id', oauthClientIdSchema),
    response: view,
  },
  {
    method: 'patch',
    path: '/v1/developer/apps/{id}',
    operationId: 'developerApps.update',
    summary: 'Update an application. Redirect changes notify active grant holders.',
    tag: 'developer',
    scopes: ['connections:admin'],
    requiresStepUp: true,
    pathParams: p('id', oauthClientIdSchema),
    body: updateOAuthAppSchema,
    response: view,
  },
  {
    method: 'post',
    path: '/v1/developer/apps/{id}/secret',
    operationId: 'developerApps.rotateSecret',
    summary: 'Rotate the secret. Both values stay valid for 24 hours.',
    tag: 'developer',
    scopes: ['connections:admin'],
    requiresStepUp: true,
    requiresIdempotencyKey: true,
    pathParams: p('id', oauthClientIdSchema),
    successStatus: 201,
    response: view,
  },
  {
    method: 'delete',
    path: '/v1/developer/apps/{id}',
    operationId: 'developerApps.delete',
    summary: 'Delete an application. Seven day soft delete.',
    tag: 'developer',
    scopes: ['connections:admin'],
    requiresStepUp: true,
    pathParams: p('id', oauthClientIdSchema),
    successStatus: 204,
  },
  {
    method: 'get',
    path: '/v1/developer/grants',
    operationId: 'developerApps.listGrants',
    summary: 'Grants users have given to applications.',
    tag: 'developer',
    scopes: ['connections:admin'],
    query: listGrantsQuerySchema,
    response: pagedView,
  },
  {
    method: 'delete',
    path: '/v1/developer/grants/{id}',
    operationId: 'developerApps.revokeGrant',
    summary: 'Revoke a grant. Effective within seconds.',
    tag: 'developer',
    scopes: ['connections:admin'],
    pathParams: p('id', oauthGrantIdSchema),
    successStatus: 204,
  },

  /* ----------------------------------------------------------------- audit */
  {
    method: 'get',
    path: '/v1/audit-events',
    operationId: 'audit.list',
    summary: 'The audit log. Append only, same identity model on every surface.',
    tag: 'audit',
    scopes: ['connections:admin'],
    query: listAuditQuerySchema,
    response: pagedView,
  },

  /* ------------------------------------------------------- oauth provider */
  {
    method: 'get',
    path: '/oauth/authorize',
    operationId: 'oauth.authorize',
    summary: 'Begin an authorization request. PKCE with S256 is mandatory.',
    tag: 'oauth',
    workspaceOptional: true,
    query: authorizeQuerySchema,
    successStatus: 302,
  },
  {
    method: 'get',
    path: '/oauth/consent',
    operationId: 'oauth.consentData',
    summary: 'The data the consent screen renders, with scopes grouped by risk.',
    tag: 'oauth',
    workspaceOptional: true,
  },
  {
    method: 'post',
    path: '/oauth/consent',
    operationId: 'oauth.consent',
    summary: 'Record the decision and mint a 60 second single-use code.',
    tag: 'oauth',
    workspaceOptional: true,
    body: consentDecisionSchema,
  },
  {
    method: 'post',
    path: '/oauth/token',
    operationId: 'oauth.token',
    summary: 'Exchange a code or a refresh token. Scopes come from the stored grant.',
    tag: 'oauth',
    public: true,
    body: tokenRequestSchema,
  },
  {
    method: 'post',
    path: '/oauth/revoke',
    operationId: 'oauth.revoke',
    summary: 'RFC 7009 revocation. Always 200.',
    tag: 'oauth',
    public: true,
    body: revocationRequestSchema,
  },
  {
    method: 'post',
    path: '/oauth/introspect',
    operationId: 'oauth.introspect',
    summary: 'RFC 7662 introspection. Confidential clients, own tokens only.',
    tag: 'oauth',
    public: true,
    body: introspectionRequestSchema,
  },
  {
    method: 'get',
    path: '/.well-known/oauth-authorization-server',
    operationId: 'oauth.authorizationServerMetadata',
    summary: 'RFC 8414 authorization server metadata.',
    tag: 'oauth',
    public: true,
  },
  {
    method: 'get',
    path: '/.well-known/oauth-protected-resource',
    operationId: 'oauth.protectedResourceMetadata',
    summary: 'RFC 9728 protected resource metadata. Names the audience to request.',
    tag: 'oauth',
    public: true,
  },
];
