/**
 * Seeded library content for local development and tests.
 *
 * Real looking files from a plausible workspace. No customer logo, no stock
 * photography claim, no performance number attached to any asset.
 */

import type { MediaAsset } from '../types';

export const SEED_ASSETS: readonly MediaAsset[] = [
  {
    id: 'media_seed_launch_hero',
    name: 'first_comments_hero.jpg',
    kind: 'image',
    mimeType: 'image/jpeg',
    bytes: 1_842_301,
    width: 1600,
    height: 900,
    durationSeconds: null,
    checksum: 'sha256:4f19b2c8a1d0e77c3a9f0b6d2e5148c7',
    createdAt: '2026-08-02T11:04:00.000Z',
    scanState: 'clean',
    retentionExpiresAt: '2026-09-01T11:04:00.000Z',
    storageAvailable: true,
    altText:
      'A scheduling queue with a post and two follow up comments, each showing its own delay.',
    altTextWaived: false,
    altTextWaivedReason: null,
    altTextWaivedByName: null,
    rights: {
      owner: 'workspace',
      licenseReference: null,
      peopleAppear: false,
      peopleConsented: false,
      containsMusic: false,
      declaredByName: 'Ana Ruiz',
      declaredAt: '2026-08-02T11:06:00.000Z',
    },
    rightsDeclared: true,
    provenance: {
      origin: 'upload',
      sourceUrl: null,
      fetchedAt: null,
      declaredAuthor: null,
      declaredLicense: null,
      contentCredentials: null,
      addedByName: 'Ana Ruiz',
    },
    versions: [
      {
        version: 1,
        width: 1600,
        height: 900,
        bytes: 1_842_301,
        mimeType: 'image/jpeg',
        createdAt: '2026-08-02T11:04:00.000Z',
        edit: null,
      },
    ],
    currentVersion: 1,
    usedInPostCount: 2,
    thumbnailMediaId: null,
  },
  {
    id: 'media_seed_square_card',
    name: 'changelog_card_square.png',
    kind: 'image',
    mimeType: 'image/png',
    bytes: 903_112,
    width: 1080,
    height: 1080,
    durationSeconds: null,
    checksum: 'sha256:b71c2ee9f0a4d5138c6207ab5e0f9d31',
    createdAt: '2026-08-03T08:21:00.000Z',
    scanState: 'clean',
    retentionExpiresAt: '2026-09-02T08:21:00.000Z',
    storageAvailable: true,
    altText: null,
    altTextWaived: false,
    altTextWaivedReason: null,
    altTextWaivedByName: null,
    rights: null,
    rightsDeclared: false,
    provenance: {
      origin: 'import',
      sourceUrl: 'https://acme.example/press/changelog_card_square.png',
      fetchedAt: '2026-08-03T08:21:00.000Z',
      declaredAuthor: 'Acme design team',
      declaredLicense: 'Internal use',
      contentCredentials: null,
      addedByName: 'Ana Ruiz',
    },
    versions: [
      {
        version: 1,
        width: 1080,
        height: 1080,
        bytes: 903_112,
        mimeType: 'image/png',
        createdAt: '2026-08-03T08:21:00.000Z',
        edit: null,
      },
    ],
    currentVersion: 1,
    usedInPostCount: 0,
    thumbnailMediaId: null,
  },
  {
    id: 'media_seed_walkthrough',
    name: 'first_comments_walkthrough.mp4',
    kind: 'video',
    mimeType: 'video/mp4',
    bytes: 48_221_904,
    width: 1920,
    height: 1080,
    durationSeconds: 78,
    checksum: 'sha256:0c3d99a7be145f2810d6ab34ff0921ce',
    createdAt: '2026-08-01T16:40:00.000Z',
    scanState: 'clean',
    retentionExpiresAt: '2026-08-31T16:40:00.000Z',
    storageAvailable: true,
    altText: null,
    altTextWaived: true,
    altTextWaivedReason: 'The video carries captions and a spoken description.',
    altTextWaivedByName: 'Ana Ruiz',
    rights: {
      owner: 'workspace',
      licenseReference: null,
      peopleAppear: true,
      peopleConsented: true,
      containsMusic: false,
      declaredByName: 'Ana Ruiz',
      declaredAt: '2026-08-01T16:45:00.000Z',
    },
    rightsDeclared: true,
    provenance: {
      origin: 'upload',
      sourceUrl: null,
      fetchedAt: null,
      declaredAuthor: null,
      declaredLicense: null,
      contentCredentials: 'c2pa: signed by Acme capture tool',
      addedByName: 'Marco Silva',
    },
    versions: [
      {
        version: 1,
        width: 1920,
        height: 1080,
        bytes: 48_221_904,
        mimeType: 'video/mp4',
        createdAt: '2026-08-01T16:40:00.000Z',
        edit: null,
      },
    ],
    currentVersion: 1,
    usedInPostCount: 1,
    thumbnailMediaId: 'media_seed_square_card',
  },
];
