/**
 * `@relay/billing`
 *
 * Polar as merchant of record, the webhook inbox, derived entitlements,
 * reconciliation, provider usage metering, the trial, affiliate accounting and
 * the unit-economics model.
 *
 * Three rules hold across the whole package:
 *  - tiers buy active project capacity and nothing else. Every tier includes
 *    every feature. The base tier is $29 a month or $300 a year and includes
 *    three active projects, with a seven day trial on both intervals and the
 *    annual saving stated in money, never as a percentage;
 *  - entitlements come only from verified subscription state plus periodic
 *    reconciliation, never from the checkout success redirect;
 *  - there is no AI image or video generation product, meter or entitlement.
 */

export {
  ANNUAL_EFFECTIVE_MONTHLY_MINOR,
  ANNUAL_PRICE_MINOR,
  ANNUAL_PRODUCT,
  ANNUAL_SAVING_BASIS_POINTS,
  ANNUAL_SAVING_MINOR,
  ACTIVE_CHANNEL_ALLOWANCE,
  BILLING_INTERVALS,
  FORBIDDEN_BILLING_PHRASES,
  GRACE_PERIOD_DAYS,
  MANDATED_COPY,
  MEMBER_ALLOWANCE,
  MONTHLY_PRICE_MINOR,
  MONTHLY_PRODUCT,
  PLAN_CURRENCY,
  PLAN_INCLUSION_KEYS,
  PLAN_KEY,
  PLAN_PRODUCTS,
  POLAR_TRIAL_REMINDER_DAY,
  POLAR_TRIAL_REMINDER_LEAD_DAYS,
  PRICE_PRESENTATION,
  READ_ONLY_PERIOD_DAYS,
  RELAY_TRIAL_SUMMARY_DAY,
  TIER_PRESENTATIONS,
  TRIAL_DAYS,
  billingIntervalSchema,
  derivedAnnualFramingAmounts,
  normalizeInterval,
  planPriceMinor,
  planProduct,
  trialLengthMatches,
  type AnnualFramingPresentation,
  type BillingInterval,
  type IntervalPresentation,
  type PlanProduct,
  type PricePresentation,
} from './products';

export {
  BASE_TIER_KEY,
  FOUNDER_DECISION_PENDING,
  FOUNDER_DECISION_PENDING_ENV_KEY,
  PENDING_TIER_KEYS,
  PLAN_TIERS,
  PLAN_TIER_KEYS,
  PUBLISHABLE_TIER_KEYS,
  SHARED_INCLUSION_KEYS,
  assertTierPublishable,
  isPublishableTier,
  planTier,
  planTierKeySchema,
  publishableTiers,
  tierDecisionPending,
  productTiersFromProductIds,
  tierForProductId,
  tierInclusionKeys,
  tierPriceMinor,
  tierProjectAllowance,
  type PlanTier,
  type PlanTierKey,
} from './tiers';

export {
  TIER_ANNUAL_FRAMING_KEY,
  TIER_PROJECT_ALLOWANCE_KEY,
  buildTierPresentation,
  publishableTierPresentations,
  tierPresentationStrings,
  type TierAnnualFraming,
  type TierIntervalPresentation,
  type TierPresentation,
} from './tier-presentation';

export {
  PROJECT_ALLOWANCE_ENTITLEMENT_KEY,
  buildProjectAllowanceGrant,
  projectCapacityPosture,
  type BuildProjectAllowanceGrantInput,
  type ProjectAllowanceGrant,
  type ProjectCapacityPosture,
} from './project-allowance';

export {
  POST_CREDIT_KEY,
  POST_CREDIT_NOTICE_THRESHOLD,
  buildPostCreditGrant,
  postCreditPosture,
  signupPostCreditGrant,
  type BuildPostCreditGrantInput,
  type PostCreditGrant,
  type PostCreditPosture,
  type PostCreditPostureInput,
  type PublishingPlan,
} from './post-credits';

export {
  MICRO_PER_MINOR,
  MICRO_PER_UNIT,
  MINOR_PER_UNIT,
  USD,
  addMoney,
  applyBasisPoints,
  formatMicro,
  formatMoneyMinor,
  microRemainder,
  microToMinor,
  minorToMicro,
  money,
  negateMoney,
  sumMoney,
  unitsToMicro,
  unitsToMinor,
  type FormatMoneyOptions,
} from './money';

export {
  MILLISECONDS_PER_DAY,
  MutableClock,
  SECONDS_PER_DAY,
  addDays,
  addMonths,
  addSeconds,
  addYears,
  daysUntil,
  differenceDays,
  differenceMs,
  fixedClock,
  isAfter,
  isAtOrAfter,
  isBefore,
  isoDateOf,
  maxInstant,
  normalizeInstant,
  nowIso,
  parseInstant,
  systemClock,
  toIsoInstant,
  type Clock,
} from './time';

export { BILLING_MESSAGE_KEYS, type BillingMessageKey } from './messages';

export {
  POLAR_EVENT_TYPES,
  isKnownPolarEventType,
  polarBenefitGrantSchema,
  polarCheckoutSchema,
  polarCustomerSchema,
  polarCustomerSessionSchema,
  polarOrderSchema,
  polarProductSchema,
  polarSubscriptionSchema,
  polarWebhookBodySchema,
  type PolarBenefitGrant,
  type PolarCheckout,
  type PolarCustomer,
  type PolarCustomerSession,
  type PolarEventType,
  type PolarOrder,
  type PolarProduct,
  type PolarSubscription,
} from './polar-schemas';

export {
  HttpPolarClient,
  POLAR_API_BASE_URLS,
  createPolarClient,
  isSimulated,
  polarClientFromSdk,
  type CancelSubscriptionInput,
  type CreateCheckoutInput,
  type CreatePolarClientOptions,
  type HttpPolarClientOptions,
  type ListSubscriptionsInput,
  type ListSubscriptionsResult,
  type PolarClient,
  type PolarSdkLike,
  type UsageEventInput,
} from './client';

export {
  LocalPolarSimulator,
  SIMULATOR_ANNUAL_PRODUCT_ID,
  SIMULATOR_BENEFIT_ID,
  SIMULATOR_HOST,
  SIMULATOR_MONTHLY_PRODUCT_ID,
  SIMULATOR_WEBHOOK_SECRET,
  type LocalPolarSimulatorOptions,
  type SimulatedDelivery,
} from './simulator';

export {
  DEFAULT_TOLERANCE_SECONDS,
  WEBHOOK_HEADER_ID,
  WEBHOOK_HEADER_SIGNATURE,
  WEBHOOK_HEADER_TIMESTAMP,
  constantTimeEquals,
  decodeSigningSecret,
  hashBody,
  signWebhook,
  verifyWebhookSignature,
  type SignatureFailure,
  type SignatureVerification,
  type SignWebhookInput,
  type VerifyWebhookInput,
} from './signature';

export {
  CHECKOUT_RETURN_POLL_SECONDS,
  DISCLOSURE_VERSION,
  REQUIRED_DISCLOSURE_LINE_IDS,
  REQUIRED_IMMEDIATE_DISCLOSURE_LINE_IDS,
  requiredDisclosureLineIds,
  buildCheckoutDisclosure,
  buildConsentRecord,
  checkoutReturnState,
  createCheckoutSession,
  resolveProductId,
  tierProductKey,
  type ResolveProductIdInput,
  type CheckoutDeps,
  type CheckoutDisclosure,
  type CheckoutReturnState,
  type CheckoutSession,
  type CreateCheckoutSessionInput,
  type DisclosureConsentRecord,
  type DisclosureLine,
} from './checkout';

export {
  InMemorySubscriptionStore,
  InMemoryWebhookInbox,
  WEBHOOK_RESULTS,
  WEBHOOK_SIGNATURE_STATES,
  type MarkProcessedInput,
  type NewWebhookInboxRecord,
  type SubscriptionStore,
  type WebhookInboxRecord,
  type WebhookInboxStore,
  type WebhookResult,
  type WebhookSignatureState,
} from './inbox';

export {
  WEBHOOK_FAILURE_ALERT_THRESHOLD,
  createInMemoryWebhookStores,
  createWebhookProcessor,
  shouldAlertOnFailure,
  toVerifiedSubscription,
  workspaceIdOf,
  type EntitlementChange,
  type IncomingWebhook,
  type OrderEvent,
  type WebhookOutcome,
  type WebhookProcessor,
  type WebhookProcessorDeps,
} from './webhooks';

export {
  ALWAYS_ALLOWED_ACTIONS,
  BILLING_ACTIONS,
  CONSUMING_ACTIONS,
  ENTITLEMENT_REASONS,
  ENTITLEMENT_STATES,
  SCHEDULED_POST_DISPOSITIONS,
  SUBSCRIPTION_SOURCES,
  VERIFIED_SUBSCRIPTION_SOURCES,
  channelAllowanceExceeded,
  deriveEntitlement,
  entitlementError,
  evaluateEntitlement,
  isFullAccess,
  isVerifiedSource,
  scheduledPostDisposition,
  tierOf,
  verifiedSubscriptionSchema,
  type BillingAction,
  type DeriveEntitlementOptions,
  type EntitlementDecision,
  type EntitlementEffect,
  type EntitlementReason,
  type EntitlementSnapshot,
  type EntitlementState,
  type EvaluateEntitlementOptions,
  type ScheduledPostDisposition,
  type SubscriptionSource,
  type VerifiedSubscription,
} from './entitlements';

export {
  DRIFT_PAGE_THRESHOLD_PER_HOUR,
  FULL_SWEEP_INTERVAL_HOURS,
  INITIAL_LOOKBACK_DAYS,
  RECONCILIATION_INTERVAL_MINUTES,
  reconcileSubscriptions,
  reconcileWorkspace,
  type DriftKind,
  type DriftRecord,
  type ReconcileDeps,
  type ReconcileInput,
  type ReconciliationReport,
} from './reconcile';

export {
  CANCELLATION_OFFER_KEYS,
  TRIAL_DUE_TODAY_MINOR,
  TRIAL_METERED_SPEND_CAP_MINOR,
  TRIAL_PHASES,
  assertTrialConfiguration,
  cancellationOutcome,
  computeTrialSchedule,
  polarReminderAlignmentIsValid,
  trialStatus,
  type CancellationInput,
  type CancellationOutcome,
  type ComputeTrialScheduleInput,
  type TrialPhase,
  type TrialSchedule,
  type TrialStatus,
} from './trial';

export {
  DEFAULT_SPEND_CONTROLS,
  FORBIDDEN_METER_NAMES,
  HARD_PAUSE_DEFAULT,
  METERED_OPERATIONS,
  PRICE_BOOK_MAX_AGE_DAYS,
  SPEND_ALERT_DEFAULT_MINOR,
  TRIAL_SPEND_CAP_MINOR,
  X_PRICE_BOOK,
  assertMeterAllowed,
  createAiTextPriceBook,
  estimateUsage,
  evaluateSpendControls,
  isPriceBookStale,
  mergePriceBooks,
  nextUsagePeriodStart,
  periodTotal,
  priceBookVerifiedAt,
  priceFor,
  publishUsage,
  reconcileUsage,
  recordUsage,
  toPolarUsageEvents,
  usageMeterName,
  xPostOperation,
  type MeteredOperation,
  type PriceBook,
  type PriceBookEntry,
  type SpendControls,
  type SpendDecision,
  type UsageAdjustment,
  type UsageEstimate,
  type UsageEstimateLine,
  type UsageOperation,
  type UsageRecord,
} from './usage';

export {
  AFFILIATE_TERMS,
  FRAUD_THRESHOLDS,
  FRAUD_TRIGGERS,
  InMemoryCommissionLedger,
  LEDGER_ENTRY_TYPES,
  MONETARY_ENTRY_TYPES,
  PAYOUT_BATCH_STATES,
  REFERRAL_CHANNELS,
  accrueCommission,
  attributeReferral,
  buildPayoutBatch,
  commissionBalance,
  daysHeld,
  evaluateFraudTriggers,
  isWithinCommissionWindow,
  reverseCommission,
  type AccrualResult,
  type AccrueCommissionInput,
  type AttributeReferralInput,
  type AttributionRefusal,
  type AttributionResult,
  type BuildPayoutBatchResult,
  type CommissionBalance,
  type CommissionLedger,
  type CommissionLedgerEntry,
  type FraudReview,
  type FraudSignals,
  type FraudTrigger,
  type LedgerEntryType,
  type PayoutBatch,
  type PayoutBatchState,
  type ReferralAttribution,
  type ReferralChannel,
  type ReferralTouch,
  type ReversalKind,
} from './affiliate';

export {
  DOCUMENTED_ASSUMPTIONS,
  FORBIDDEN_MARGIN_LEVERS,
  MARGIN_GATE_BASIS_POINTS,
  MARGIN_GATE_SUBSCRIBERS,
  MARGIN_LEVERS,
  REFERRED_COHORT_MARGIN_FLOOR_BASIS_POINTS,
  REPORTED_SCALES,
  blendedEconomics,
  marginTable,
  planEconomics,
  referredCohortEconomics,
  subscribersToMeetMarginGate,
  type BlendedEconomics,
  type EconomicsAssumptions,
  type MarginTableRow,
  type PlanEconomics,
  type ReferredCohortEconomics,
} from './economics';
